### ISSUE TITLE
Error: easy handled already used in multi handle

### ISSUE THREAD

**Issue by noamross** [hadley/httr#112]
Sometimes `GET()` returns the error:

```
Error in function (type, msg, asError = TRUE)  : 
  easy handled already used in multi handle
```

I'm having trouble isolating the exact cause, but it seems to occur when I've performed at least one `GET()` request in my session, possibly only if I've aborted the function before it completed.

**Comment by aronlindberg** [comment]
I am using rgithub and I have httr 0.6.1. loaded (which rgithub depends on). This seems to generate this error again. Is there a newer version to use, or a workaround?

**Comment by overvolting** [comment]
I can confirm I've just experienced the same error from the cran version.

**Comment by 1beb** [comment]
+1 for this error.

**Comment by Ironholds** [comment]
+1 (and a note that it's infected rvest)

**Comment by neverfox** [comment]
Same here when calling GET from within a function passed to `pbsapply`. However, it works fine with regular `sapply`.
