### ISSUE TITLE
Is there an option to close a connection following use?

### ISSUE THREAD

**Issue by timwilliate** [hadley/httr#122]
After successfully making GET requests to a private API, I noticed the following text at the end of the (verbose) output:

```
Connection #0 to host {host_name} left intact
```

I can see from the httr documentation that by default, connections are left open and then reused.  Is there a method which can be used to explicitly close all open connections?  I would like to perform such an operation after executing a series of GET requests in order to ensure that no http connections are left open on the server.

Thank you

**Comment by datafj** [comment]
> You could also do:
> 
> ```r
> GET(..., config(forbid.reuse = 1))
> ```

Actually it is `GET(..., config(forbid_reuse = 1))`, with an underscore between forbid and reuse, not a period.
