### ISSUE TITLE
Twitter authentification not working anymore

### ISSUE THREAD

**Issue by joelgombin** [hadley/httr#156]
I get a 401 error when trying to replicate the twitter demo. The only difference between the demo code and mine is that I pass the secret through the call to `oauth_app`.

Here is the log:

``` r
> oauth_endpoints("twitter")
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
> myapp <- oauth_app("twitter", key = "XXXXXXXXXXXX", secret = "XXXXXXXXXXXXXXXXXXXXXXX")
> twitter_token <- oauth1.0_token(oauth_endpoints("twitter"), myapp)
Use a local file to cache OAuth access credentials between R sessions?
1: Yes
2: No

Selection: Yes
Error in init_oauth1.0(endpoint, app, permission = params$permission) : 
  client error: (401) Unauthorized
```

and here is my session info:

``` r
> sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C         LC_TIME=C            LC_COLLATE=C         LC_MONETARY=C       
 [6] LC_MESSAGES=C        LC_PAPER=C           LC_NAME=C            LC_ADDRESS=C         LC_TELEPHONE=C      
[11] LC_MEASUREMENT=C     LC_IDENTIFICATION=C 

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] httr_0.5.0.9000  shiny_0.10.2.1   ggvis_0.3.0.9003 scales_0.2.4     ggplot2_1.0.0    devtools_1.6     doParallel_1.0.8
 [8] iterators_1.0.7  foreach_1.4.2    lubridate_1.3.3  dplyr_0.3        RMySQL_0.9-3     DBI_0.3.1       

loaded via a namespace (and not attached):
 [1] MASS_7.3-34      R6_2.0           RCurl_1.95-4.3   RJSONIO_1.3-0    Rcpp_0.11.3      assertthat_0.1   codetools_0.2-9 
 [8] colorspace_1.2-4 digest_0.6.4     evaluate_0.5.5   formatR_1.0      grid_3.1.1       gtable_0.1.2     htmltools_0.2.6 
[15] httpuv_1.3.0     knitr_1.6        magrittr_1.0.1   mime_0.2         munsell_0.4.2    plyr_1.8.1       proto_0.3-10    
[22] reshape2_1.4     rmarkdown_0.3.3  stringr_0.6.2    tools_3.1.1      xtable_1.7-3     yaml_2.1.13     
```

**Comment by bs77** [comment]
Hi Hadley -- were you able to resolve the problem that joelgombin was having? I am stuck at the same place/error, can I send you a screenshot from apps.twitter.com? Which page/info would you want to see?

**Comment by bs77** [comment]
Actually, everything else is the same, but my error returned is somewhat different so maybe worth including:

Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission) : 
  client error: (401) Unauthorized

**Comment by hadley** [comment]
That looks like the same error to me. I think the main thing to check is that you have http://127.0.0.1:1410 in the Callback URL and then double check you've copied the application key & secret correctly.

**Comment by bs77** [comment]
Ah, that did the trick. I had left the Callback URL field blank. 

Now I have to make heads/tails from the response object I get back, but that's a much better problem to address, happy to work away at it for a while.

Thanks!

**Comment by nil86** [comment]
cred=setup_twitter_oauth(consumer_key="yPcCaHSUlaFjqbpWpjNeA",
+ consumer_secret="UpRfKB5zd3l6Xx1SszoWpEHvBY2iNKLEarlk4o5NvNs")
[1] "Using browser based authentication"
Use a local file to cache OAuth access credentials between R sessions?
1: Yes
2: No

Selection: 1
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort

when i wrote above command into R console, token was generated on web and asking me to enter this PIN on twitter account to complete the authorisation process, but i am not understand where to enter this code.

Can somebody help me here?

Thanks!

**Comment by parinfuture** [comment]
@nil86 Here's a turn around that will work for you, rather than going for the browser based authentication. Change the defaults value here and provide values of access_token and access_secret, that will do the local verificaiton. :+1: 
setup_twitter_oauth(consumer_key, consumer_secret, access_token=NULL, access_secret=NULL)

**Comment by davogezu** [comment]
I had the same problem using RStuio with R 3.3.0. I did these:

Installed the two packages:
install.packages("openssl")
install.packages("httpuv")

Change the callback URL to http://127.0.0.1:1410  and regenerate the keys.

Run as follows:

setup_twitter_oauth(consumer_key="XX",consumer_secret="YY", access_token=NULL, access_secret=NULL)

It works now. Good luck.

**Comment by wordsmith189** [comment]
Good morning,

Same problem here - I'm stuck at:
<img width="631" alt="screen shot 2017-04-05 at 8 49 08 am" src="https://cloud.githubusercontent.com/assets/11275320/24708560/d4e4cff6-19dc-11e7-9e9e-76eecc37224e.png">

I followed all suggestions I could find, esp. on this page, and did the following:
* In the app settings, set the callback URL to http://127.0.0.1:1410
* Re-generated API key, API secret, access token, and access token secret
* Restarted my R session
* Installed and loaded packages ``openssl`` and ``httpuv`` as well as ``twitteR``
* Ran this code to try to initiate oAuth:
```
api_key <- "xxx"
api_secret <- "xxx"
access_token <- "777-xxx"
access_token_secret <- "xxx"
setup_twitter_oauth(api_key,api_secret, access_token=NULL, access_secret=NULL)
```
But all I keep getting is that same error message re: browser-based authentication (see screenshot above).

Is there anything else I could do? - FWIW, here's a screenshot of my app settings.

<img width="674" alt="screen shot 2017-04-05 at 8 51 51 am" src="https://cloud.githubusercontent.com/assets/11275320/24708961/0fa06dac-19de-11e7-928e-4a87865592cd.png">

**Comment by ddten** [comment]
@hadley 
I wrote a code like this:
library(devtools)
devtools::install_github("jrowen/twitteR", ref = "oauth_httr_1_0")
library(httr)
library(bit64)
library(base64enc)

reqtokenURL <- "https://api.twitter.com/oauth/request_token"
accesstokenURL <- "https://api.twitter.com/oauth/access_token"
authorizeURL <- "https://api.twitter.com/oauth/authorize"
api_key <- " hWooPUh9ZHlxvT0gCDUuP2Gjy"
api_secret <- "3qPY2RrwuW4FhsCYIbvjwbzEhhgS1MMeWLs2LjPFauR2QqHuCs"
access_token <- "2582011494-pZm7U7NJTaePBHKk5jWqfEc5Uf9hqHidrnpPk7Z"
access_secret <- "IwTm3e9zYAK0ZIorzeft8JeyaQP6q1TK1TGNKj1ncMv2p"

setup_twitter_oauth(api_key,api_secret,access_token,access_secret)
I am getting the error- Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'
Can you help me please? It's urgent.

**Comment by monitotier** [comment]
I am also having poblems. I installed rtweet and twitterR and with both I have problems.
I have RStudio instaled: R version 3.4.1. Windows 10 64 bits.
I have followed the instructions step by step (https://medium.com/@GalarnykMichael/accessing-data-from-twitter-api-using-r-part1-b387a1c7d3e)  including defining the Callback URL	http://127.0.0.1:1410.
Using TwitterR i got the next message: 
**[1] "Using direct authentication"
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'**
I have checked my keys several times, update them and nothing seems to work. I also checked the packages **httr**, **digest**, **curl**. too many dependencies.  
With the  Rtweet: 
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401).

Please, I do not what else to do, I have checked threads about it and nothing seems to work.  Does anyone have a hint?

**Comment by ddten** [comment]
Did you change the working directory? Also you can regenerate the keys and tokens.



On 25-Apr-2018, at 12:26 PM, monitotier <notifications@github.com<mailto:notifications@github.com>> wrote:


I am also having poblems. I installed rtweet and twitterR and with both I have problems.
I have RStudio instaled: R version 3.4.1. Windows 10 64 bits.
I have followed the instructions step by step (https://medium.com/@GalarnykMichael/accessing-data-from-twitter-api-using-r-part1-b387a1c7d3e) including defining the Callback URL http://127.0.0.1:1410.
Using TwitterR i got the next message:
[1] "Using direct authentication"
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'
I have checked my keys several times, update them and nothing seems to work. I also checked the packages httr, digest, curl. too many dependencies.
With the Rtweet:
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission, :
Unauthorized (HTTP 401).

Please, I do not what else to do, I have checked threads about it and nothing seems to work. Does anyone have a hint?

**Comment by drishti26** [comment]
I am working on an office computer where there are administrative issues as it is already, now I don't understand it is due to that or is it that due to some problem in my code? 
>if (!require("twitteR")) {
+   install.packages("twitteR")
+   library(twitteR)
+ }
Loading required package: twitteR
> if (!require("devtools")) {
+   install.packages("devtools")
+   library(devtools)
+ }
Loading required package: devtools
> if (!require("jsonlite")) {
+   install.packages("jsonlite")
+   library(jsonlite)
+ }
Loading required package: jsonlite
> if (!require("httr")) {
+   install.packages("httr")
+   library(httr)
+ }
> 
> if (!require("ggplot2")) {
+   install.packages("ggplot2")
+   library(httr)
+ }

twitteR::setup_twitter_oauth("Consumer Key", "Consumer Secret",access_token=NULL, access_secret=NULL)
[1] "Using browser based authentication"
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401).

**Comment by cderv** [comment]
FWIW, for twitter access from R, [twitteR](https://github.com/geoffjentry/twitteR) 📦 has been DEPRECATED (See the note in the README) in favor of [rtweet](https://github.com/mkearney/rtweet) 📦 . 
I think it will work better and if a there is a bug, it will be fixed.

**Comment by beakly** [comment]
Hi, sorry to revisit this issue again but I got a 403 error when trying to replicate the twitter demo. Log below:

```
> oauth_endpoints("twitter")
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
> myapp <- oauth_app("twitter",
+                    key = "XXXXXXXXXXXXXXXXXXXXXXXXX",
+                    secret = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
+ )
> twitter_token <- oauth1.0_token(oauth_endpoints("twitter"), myapp)
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Forbidden (HTTP 403).
```
I have set app callback URL to 127.0.0.1:1410, screenshot below. Also I've checked my api key and secret. Not really sure what else I'm doing wrong here. Any help would be appreciated.
<img width="254" alt="screen shot 2018-12-08 at 6 52 21 pm" src="https://user-images.githubusercontent.com/13513995/49682528-8c844400-fb1a-11e8-8732-02e056483a16.png">

Session info as follows:
```
> session_info()
─ Session info ─────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       macOS  10.14.1              
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_NZ.UTF-8                 
 ctype    en_NZ.UTF-8                 
 tz       Pacific/Auckland            
 date     2018-12-08                  

─ Packages ─────────────────────────────────────────────────────────────────────────
 package      * version    date       lib source                         
 assertthat     0.2.0      2017-04-11 [1] CRAN (R 3.5.0)                 
 backports      1.1.2      2017-12-13 [1] CRAN (R 3.5.0)                 
 base64enc      0.1-3      2015-07-28 [1] CRAN (R 3.5.0)                 
 bindr          0.1.1      2018-03-13 [1] CRAN (R 3.5.0)                 
 bindrcpp       0.2.2      2018-03-29 [1] CRAN (R 3.5.0)                 
 broom          0.5.1      2018-12-05 [1] CRAN (R 3.5.0)                 
 callr          3.0.0      2018-08-24 [1] CRAN (R 3.5.0)                 
 cellranger     1.1.0      2016-07-27 [1] CRAN (R 3.5.0)                 
 cli            1.0.1      2018-09-25 [1] CRAN (R 3.5.0)                 
 colorspace     1.3-2      2016-12-14 [1] CRAN (R 3.5.0)                 
 crayon         1.3.4      2017-09-16 [1] CRAN (R 3.5.0)                 
 curl           3.2        2018-03-28 [1] CRAN (R 3.5.0)                 
 desc           1.2.0      2018-05-01 [1] CRAN (R 3.5.0)                 
 devtools     * 2.0.1.9000 2018-12-08 [1] Github (r-lib/devtools@a6bbe87)
 digest         0.6.18     2018-10-10 [1] CRAN (R 3.5.0)                 
 dplyr        * 0.7.8      2018-11-10 [1] CRAN (R 3.5.0)                 
 forcats      * 0.3.0      2018-02-19 [1] CRAN (R 3.5.0)                 
 fs             1.2.6      2018-08-23 [1] CRAN (R 3.5.0)                 
 generics       0.0.2      2018-11-29 [1] CRAN (R 3.5.0)                 
 GGally       * 1.4.0      2018-05-17 [1] CRAN (R 3.5.0)                 
 ggplot2      * 3.1.0      2018-10-25 [1] CRAN (R 3.5.0)                 
 glue           1.3.0      2018-07-17 [1] CRAN (R 3.5.0)                 
 gridExtra    * 2.3        2017-09-09 [1] CRAN (R 3.5.0)                 
 gtable         0.2.0      2016-02-26 [1] CRAN (R 3.5.0)                 
 haven          2.0.0      2018-11-22 [1] CRAN (R 3.5.0)                 
 hms            0.4.2      2018-03-10 [1] CRAN (R 3.5.0)                 
 httpuv       * 1.4.5      2018-07-19 [1] CRAN (R 3.5.0)                 
 httr         * 1.3.1      2017-08-20 [1] CRAN (R 3.5.0)                 
 jsonlite       1.5        2017-06-01 [1] CRAN (R 3.5.0)                 
 later          0.7.5      2018-09-18 [1] CRAN (R 3.5.0)                 
 lattice        0.20-38    2018-11-04 [1] CRAN (R 3.5.0)                 
 lazyeval       0.2.1      2017-10-29 [1] CRAN (R 3.5.0)                 
 lubridate    * 1.7.4      2018-04-11 [1] CRAN (R 3.5.0)                 
 magrittr       1.5        2014-11-22 [1] CRAN (R 3.5.0)                 
 memoise        1.1.0      2017-04-21 [1] CRAN (R 3.5.0)                 
 modelr         0.1.2      2018-05-11 [1] CRAN (R 3.5.0)                 
 munsell        0.5.0      2018-06-12 [1] CRAN (R 3.5.0)                 
 nlme           3.1-137    2018-04-07 [1] CRAN (R 3.5.1)                 
 openssl        1.1        2018-11-15 [1] CRAN (R 3.5.0)                 
 pillar         1.3.0      2018-07-14 [1] CRAN (R 3.5.0)                 
 pkgbuild       1.0.2      2018-10-16 [1] CRAN (R 3.5.0)                 
 pkgconfig      2.0.2      2018-08-16 [1] CRAN (R 3.5.0)                 
 pkgload        1.0.2      2018-10-29 [1] CRAN (R 3.5.0)                 
 plyr           1.8.4      2016-06-08 [1] CRAN (R 3.5.0)                 
 prettyunits    1.0.2      2015-07-13 [1] CRAN (R 3.5.0)                 
 processx       3.2.1      2018-12-05 [1] CRAN (R 3.5.0)                 
 promises       1.0.1      2018-04-13 [1] CRAN (R 3.5.0)                 
 ps             1.2.1      2018-11-06 [1] CRAN (R 3.5.0)                 
 purrr        * 0.2.5      2018-05-29 [1] CRAN (R 3.5.0)                 
 R6             2.3.0      2018-10-04 [1] CRAN (R 3.5.0)                 
 RColorBrewer * 1.1-2      2014-12-07 [1] CRAN (R 3.5.0)                 
 Rcpp           1.0.0      2018-11-07 [1] CRAN (R 3.5.0)                 
 readr        * 1.2.1      2018-11-22 [1] CRAN (R 3.5.0)                 
 readxl         1.1.0      2018-04-20 [1] CRAN (R 3.5.0)                 
 remotes        2.0.2      2018-10-30 [1] CRAN (R 3.5.0)                 
 reshape        0.8.8      2018-10-23 [1] CRAN (R 3.5.0)                 
 reshape2     * 1.4.3      2017-12-11 [1] CRAN (R 3.5.0)                 
 rlang          0.3.0.1    2018-10-25 [1] CRAN (R 3.5.0)                 
 rprojroot      1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                 
 rstudioapi     0.8        2018-10-02 [1] CRAN (R 3.5.0)                 
 rvest          0.3.2      2016-06-17 [1] CRAN (R 3.5.0)                 
 scales         1.0.0      2018-08-09 [1] CRAN (R 3.5.0)                 
 sessioninfo    1.1.1      2018-11-05 [1] CRAN (R 3.5.0)                 
 stringi        1.2.4      2018-07-20 [1] CRAN (R 3.5.0)                 
 stringr      * 1.3.1      2018-05-10 [1] CRAN (R 3.5.0)                 
 tibble       * 1.4.2      2018-01-22 [1] CRAN (R 3.5.0)                 
 tidyr        * 0.8.2      2018-10-28 [1] CRAN (R 3.5.0)                 
 tidyselect     0.2.5      2018-10-11 [1] CRAN (R 3.5.0)                 
 tidyverse    * 1.2.1      2017-11-14 [1] CRAN (R 3.5.0)                 
 usethis      * 1.4.0      2018-08-14 [1] CRAN (R 3.5.0)                 
 withr          2.1.2      2018-03-15 [1] CRAN (R 3.5.0)                 
 xml2           1.2.0      2018-01-24 [1] CRAN (R 3.5.0)                 
 yaml           2.2.0      2018-07-25 [1] CRAN (R 3.5.0)                 

[1] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
```
