### ISSUE TITLE
Difficult to use httr with JSON api's

### ISSUE THREAD

**Issue by robertzk** [hadley/httr#159]
It took me a while to track down why I was able to use the Github and Hipchat API using curl, but the exact same calls through `httr::POST` were giving 400 Bad Request errors. A simple call like

``` R
httr::POST('https://api.hipchat.com/v2/rooms/room_id/notification?auth_token=token',
  body = list(message = 'hello everyone'), encode = 'json')
```

will fail. It boils down to the fact that httr uses jsonlite, where

``` R
cat(jsonlite:::toJSON(list(message = "hello from R, hipchat"))))
# {"message":["hello from R, hipchat"]}
```

whereas I suggest rjson, where

``` R
rjson::toJSON(list(message = "hello from R, hipchat")))
# {"message":"hello from R, hipchat"}
```

I understand that everything is vectorized in R, but I argue this is the wrong behavior for length 1 character vectors. `httr:::body_config` _explicitly_ and in-extensibly (except perhaps through [package stubbing](https://github.com/robertzk/testthatsomemore/blob/master/R/stub.R#L37)) forces this behavior for [all JSON calls](https://github.com/hadley/httr/blob/master/R/body.R#L38)

``` R
#  line 38 of body.R in httr
   else if (encode == "json") {
       body_raw(jsonlite::toJSON(body), "application/json")
   }
```

making it impossible to use httr to communicate with either Github or Hipchat. Potential solutions include
- Allowing the user to specify a JSON adapter (e.g., jsonlite or rjson)
- Switch to rjson which assumes length 1 character vectors should not be serialized as length 1 arrays
- Provide the `auto_unbox = TRUE` to `jsonlite::toJSON` which accomplishes the same

``` R
cat(jsonlite:::toJSON(list(message = "hello from R, hipchat"), auto_unbox = TRUE))
# {"message":"hello from R, hipchat"}
```

Let me know your preference and I will submit a pull request.

**Note**: _Something_ should be done about this, but it does require a little bit of care -- we don't want to break existing code using httr. On the other hand, there could be situations where one parameter (like `message`) _always_ expects a JSON string, whereas another parameter always expects an array, even if it is of length 1. In this situation, we would require the ability to specify which parameters to "auto-unbox". rjson has solved this problem already.

``` R
rjson::toJSON(list(unbox_this = "one", do_not_unbox = list("one")))
# {"unbox_this":"one","do_not_unbox":["one"]}
```

**Comment by RNBR** [comment]
A follow up with the solutions provided by @hadley. I got `status_code` 400 by using
``` R
response <- httr::POST(url,    
                       body= rjson::toJSON(list(a = 'a', b = 'b')),   
                       httr::content_type_json(),   
                       add_headers(Accept = 'application/json', Impersonate = ImpersonateKey)) 
```


But it worked like this:
``` R
response <- httr::POST(url,    
                       body= rjson::toJSON(list(a = 'a', b = 'b')),    
                       add_headers(Accept = 'application/json', Impersonate = ImpersonateKey)) 
```
Curious about why 😕 ? Thank you~~~

**Comment by jennybc** [comment]
I haven't read this entire thread but it looks like you should inspect what you're sending and make a direct comparison of this JSON body. That will give you more concrete info than the 400.

Use `httr::with_verbose()` prior to the call to get all the detail on what you're actually sending. In case it's helpful, [here's an example](https://github.com/r-lib/gh/commit/96f637c1ba84113fcfbf59db2a406d5aadd0cf00) of using `I()` to make sure something is packaged as an array, even if it has length 1.

**Comment by AndyMcCarthy** [comment]
I have a similar issue with using httr and json input. 

I have the following JSON:
jsontest = jsonlite::toJSON(list(variableId= jsonlite::unbox(951), treatmentId = list("950947","950948","950951")), pretty = TRUE)

Which I put into the request
response <- POST(url, body= jsontest,
                 httr::content_type_json(),                 
                 authenticate(":", ":", "ntlm"), verbose())

but I get back the error: HTTP/1.1 415 Unsupported Media Type
Any ideas where I am going wrong?

**Comment by tiernan781** [comment]
> A length-one R vector is ambiguous - should it be a js scalar or length-one js array. How is picking one as a default more dangerous than the other?





https://stackdev.space/questions/converting-json-objects-within-a-dataframe-into-a-list-using-r
