### ISSUE TITLE
Eliminate RCurl dependency

### ISSUE THREAD

**Issue by hadley** [hadley/httr#172]
Follow https://github.com/jeroenooms/curl strategy to link to system curl.

Need to implement:

* `RCurl::listCurlOptions()`
* `RCurl::getCurlOptionsConstants()`
* `RCurl::getCurlOptionTypes(constants)`
* `RCurl::curlVersion()$version`
* `RCurl::curlVersion()$ssl_version)`
* `RCurl::curlEscape()` and `RCurl::curlUnescape()`
* `RCurl::getCurlInfo()`
* `RCurl::getCurlHandle(cookiefile = cookie_path, .defaults = list())`
* `RCurl::base64(hash)`
* `RCurl::curlSetOpt()`
* `RCurl::.postForm()`
* `RCurl::curlPerform()`
* `RCurl::fileUpload()`
* `RCurl::CFILE()`
* `RCurl::binaryBuffer()`

**Comment by wibeasley** [comment]
I saw this [announced for the future R 3.2.0](http://cran.r-project.org/bin/windows/base/NEWS.R-devel.html) release.  Will this help avoid the dependency on RCurl?

>Optional use of libcurl (version 7.28.0 from Oct 2012 or later) for Internet access:
>* capabilities("libcurl") reports if this is available.
>* libcurlVersion() reports the version in use, and other details of the "libcurl" build including which URL schemes it supports.
>* curlGetHeaders() retrieves the headers for http://, https://, ftp:// and ftps:// URLs: analysis of these headers can provide insights into the ‘existence’ of a URL (it might for example be permanently redirected) and is so used in R CMD check --as-cran.
>* download.file() has a new optional method "libcurl" which will handle more URL schemes, follow redirections, and allows simultaneous downloads of multiple URLs.
>* url() has a new method "libcurl" which handles more URL schemes and follows redirections. The default method is controlled by a new option url.method, which applies also to the opening of URLs via file() (which happens implicitly in functions such as read.table.)
>* When file() or url() is invoked with a https:// or ftps:// URL which the current method cannot handle, it switches to a suitable method if one is available.
