### ISSUE TITLE
Possible embedded NUL

### ISSUE THREAD

**Issue by Ironholds** [hadley/httr#183]
>library(httr)
r <- GET("http://tools.ietf.org/html/rfc2070")
content(r, "text")
content(r, "raw")

**Comment by hadley** [comment]
The problem here is that the page claims to be UTF-8, but actually appears to be ISO-8859-1, so this works:

```R
content(r, "text", encoding = "ISO-8859-1")
```

I think the best I can do here is improve the documentation
