### ISSUE TITLE
Content function error on Windows

### ISSUE THREAD

**Issue by zhuyitan** [hadley/httr#184]
When using content function to transfer data obtained from internet to text format, an error pops up.
The commands are

a = GET("https://tcga-data.nci.nih.gov/tcgafiles/ftp_auth/distro_ftpusers/anonymous/tumor/luad/cgcc/unc.edu/illuminahiseq_rnaseqv2/rnaseqv2/unc.edu_LUAD.IlluminaHiSeq_RNASeqV2.Level_3.1.12.0/unc.edu.00481f66-1aad-4885-9162-bf802b1ed7f5.2064371.rsem.isoforms.normalized_results");
b = content(a, as = "text");

The error is 

Error in basename(file) : path too long

This error only happens for some URLs and only on Windows computer. I tried 2 Windows computers. Both of them encounter this problem. On the other 2 Mac computers, this problem does not pop up.

Please help. Thanks a lot!

**Comment by hadley** [comment]
This is an error in the mime package which httr uses: https://github.com/yihui/mime/issues/2
