### ISSUE TITLE
modify_url lose original path

### ISSUE THREAD

**Issue by unikum** [hadley/httr#185]
Hi.

```r
> modify_url(url = "http://example.com/some/path?param=value", path = "some/path2", query = list(parman = "value2"))
[1] "http://example.com/some/path2?param=value&parman=value2"
```

As you can see original path was removed. Is it bug or feature?

Now I need to combine the original and new paths.

**Comment by hadley** [comment]
Yes, `modify_url()` replaces each component with the new value.
