### ISSUE TITLE
Add application/atom+xml as a parseable type?

### ISSUE THREAD

**Issue by jennybc** [hadley/httr#189]
Context: I've placed a request to an API using `httr::GET`. Let's call the result `x`. I want to use `httr::content` on `x`.

The MIME type found in `x$headers[["content-type"]]` is `"application/atom+xml; charset=UTF-8"`, which is currently not recognized by `httr` as parseable.  Is this a MIME type that could be added right around here?
https://github.com/hadley/httr/blob/7ed5bc1167e6454dced51c13e5e2b713c0a74194/R/content-parse.r#L63

To be clear, I have been specifying the type myself, which gets the correct result: `httr::content(req, type = "text/xml")`. But maybe this MIME type is worth adding to the auto-detection list.

This warning in the `content()` help file is scaring me:

> When using content() in a package, DO NOT use on as = "parsed". Instead, check the mime-type is what you expect, and then parse yourself. This is safer, as you will fail informatively if the API changes, and you will protect yourself against changes to httr.

My usage __is__ in a package. Am I doing something dangerous with this: `httr::content(req, type = "text/xml")`? Are you advising me to explicitly check that the MIME type is what I expect ("application/atom+xml; charset=UTF-8") before the call to `content()`? I'm not sure what's meant by "parse yourself". I like the way `content()` dispatches the correct parser once I've set the type correctly.  Am I supposed to be doing something even more low-level for safety's sake?

**Comment by jennybc** [comment]
Bump! Now that you've seen this XML in more detail.

**Comment by hadley** [comment]
Yeah, I think you should be parsing this yourself, with e.g., `xml2::xml(context(r, "raw"))`
