### ISSUE TITLE
GET on FTP URL returns empty status_code()

### ISSUE THREAD

**Issue by dtenenba** [hadley/httr#190]
```r
library(httr)
response <- GET("ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b142_GRCh38/VCF/common_all_20150114_papu.vcf.gz.tbi")
status_code(response) # integer(0)
```

Even though it looks like the download completed fine and I can write it out:

```
bin <- content(response, "raw")
writeBin(bin, "/tmp/myfile")

```

Comparing the size and md5sum of the file downloaded here vs. the same file downloaded to a different directory using my web browser, indicates the two files have identical contents. So the download succeeded, but I don't really have any way of knowing that (do I?) because the status code of the response is empty. I understand that this is an FTP request, not an HTTP request, so maybe I should not expect an HTTP status code here, but I'm not sure how I can tell programmatically if the request was successful. 

Thanks.
```
 Under development (unstable) (2015-01-26 r67627)
Platform: x86_64-apple-darwin10.8.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] httr_0.6.1

loaded via a namespace (and not attached):
[1] stringr_0.6.2

```

**Comment by Ironholds** [comment]
I guess what you really want is the [FTP return code](https://en.wikipedia.org/wiki/List_of_FTP_server_return_codes)?

I'm not knowledgeable enough about how RCurl/Curl handles FTP to say how it might be retrieved, but some experimentation I did with the above code indicates that server-side errors are passed to RCurl, and result in a stop. So if we point to a file that doesn't exist:

> response2 <- GET("ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b142_GRCh38/VCF/common_all_201fsdfsd50114_papu.vcf.gz.tbi")
Error in function (type, msg, asError = TRUE)  : RETR response: 550

So, you can at least see if it *didn't* work ;p. Not sure if this applies to all possible negative responses, however.

**Comment by hadley** [comment]
I don't have any plans to support ftp in httr.
