### ISSUE TITLE
option for `use_obb = TRUE` in oauth1.0_token?

### ISSUE THREAD

**Issue by cboettig** [hadley/httr#191]
Hi Hadley,

I'm wondering if it is possible to add an option to `oauth1.0_token()` to match the `use_obb = TRUE` option in `oauth2.0_token()`.  At least that's what I think I need.  The automatic authentication by listening for the user to finish authenticating in the browser is great when it works, but I find myself running applications needing oauth1.0 authentication from inside a Docker container where I cannot get the port listening thing to work (even when exposing the `1410` port).  Anyway, it would be great to have the manual work-around in this case where the after the user authenticates, they manually paste the code back into the terminal instead of it happening automatically with the callback.  At least, I think that's what I need in this case.  (Trying `rfigshare::fs_auth()` from inside any dockerized R container should be enough to reproduce this issue).  

Thanks!

- Carl

**Comment by hadley** [comment]
Is oob auth a standard thing for oauth 1.0?

**Comment by cboettig** [comment]
I think so: http://oauth.net/discovery/1.0/#manual_alloc, though I'm afraid I'm over my head here.  

All I can tell is that auth1.0_token() results in the browser attempting to post something to `http://localhost:1410` after authenticating, while R sets up some kind of listner.  But when running R inside a container, this post results in a 'page not found' error and the R function is just stuck listening forever. It would be nice if a user could somehow manually paste in the authentication token in this circumstance. Does that make any sense?
