### ISSUE TITLE
Advice on how to read the httr-oauth file?

### ISSUE THREAD

**Issue by lmmx** [hadley/httr#194]
I'm trying to retain access tokens on file generated upon browser authentication, but am struggling to read the `.httr-oauth` file. `file()` shows it's `class: gzfile`, but `gzfile()` won't open it

```
file.connection <- file('.httr-oauth')
Error in gzfile(file.connection) : invalid 'description' argument
```

I tried opening in Python and the decoding seems off. Can someone advise how to parse this file for user access token details in R please ?

**Comment by hadley** [comment]
Use `readRDS()`

**Comment by lmmx** [comment]
Ah thankyou. Sorry but this is still beyond what I've worked with before - it shows as a list and then within that an environment, but I can't access any of the variables shown in this environment

```
oauth_content <- readRDS('.httr-oauth')
oauth_content
$xxxx0x000xxxx00000x0xx0x000000xx


 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
 twitter
  key:    xxxxxxxxxx0xxxxxxxxxxxxxx
  secret: 
 oauth_token, oauth_token_secret, user_id, screen_name
```

I just wanted to get the objects held in there but can't with `oauth_content$xxxx0x000xxxx00000x0xx0x000000xx` or `attr(readRDS('.httr-oauth')$xxxx0x000xxxx00000x0xx0x000000xx, 'class')`

I can't see anything in the R book explaining this sort of data structure, `str()` shows classes, but the `[['string']]` I'd usually use don't work to access the content of 'Token' as in [your answer here](http://stackoverflow.com/a/6457376/2668831)... Can you suggest how I can get to those token strings please?
