### ISSUE TITLE
Apparent Memory Leak

### ISSUE THREAD

**Issue by AlexIoannides** [hadley/httr#198]
I'm running a GET request multiple times within a loop to retrieve data from an Elasticsearch server on my local machine (running OS X Yosemite). For example,

```
scroll_data <- GET( 'http://localhost:9200', path = paste0('_search/scroll?scroll=1m&scroll_id=',scroll_id))
```

Where `scroll_id` is requested once before the loop kicks off. Each response is configured to be about 4mb in size and contains lines of JSON documents.

However, despite the fact that I am always re-assigning the response to `scroll_data`, the memory used by R continues to increase (~50gb including virtual memory), until R Studio aborts the session.

Any idea why this is and how I could get around it?

**Comment by hadley** [comment]
This is probably a memory leak in RCurl :(  It'll go away when we switch from RCurl to curl

**Comment by ucbpaio** [comment]
Thanks Hadley.

**Comment by jeroenooms** [comment]
Hi Alex,

It would be great if you can help testing if the new implementation is free of memory leaks:

```r
library(devtools)
install_github("jeroenooms/curl")
```

Assuming you are doing a simple http GET, there is two scenarios to test. One is where a new handle is initiated for each request. Based on your example something like this:

```r
url <- paste0("http://localhost:9200/_search/scroll?scroll=1m&scroll_id=", scroll_id)
for(i in 1:100){
  req  <- curl_perform(url)
  stopifnot(req$status_code == 200)
}
```

The other scenario is where a single handle is reused for all requests:

```r
url <- paste0("http://localhost:9200/_search/scroll?scroll=1m&scroll_id=", scroll_id)
h <- new_handle()
for(i in 1:100){
  req  <- curl_perform(url, handle = h)
  stopifnot(req$status_code == 200)
}
```

**Comment by ucbpaio** [comment]
My pleasure - I'll get to it in a day or two.

**Comment by ucbpaio** [comment]
Hi Jeroen,

Here are the before and after process details for your two scenarios (plus an httr scenario for comparison):

__Scenario 1 (new handle):__
![screen shot 2015-03-03 at 22 27 22](https://cloud.githubusercontent.com/assets/5968486/6474024/781bcf0e-c1f5-11e4-82d0-09e2bdcb85dc.png)
![screen shot 2015-03-03 at 22 28 28](https://cloud.githubusercontent.com/assets/5968486/6474025/783d7942-c1f5-11e4-85c7-c53b517103db.png)


__Scenario 2 (single handle):__
![screen shot 2015-03-03 at 22 28 28](https://cloud.githubusercontent.com/assets/5968486/6474054/9b869c8a-c1f5-11e4-89a7-15c2e6f189fe.png)
![screen shot 2015-03-03 at 22 29 36](https://cloud.githubusercontent.com/assets/5968486/6474055/9ba61ce0-c1f5-11e4-9757-fa369bfc0538.png)


__Scenario 3 (httr):__
```
url <- paste0("http://localhost:9200/_search/scroll?scroll=1m&scroll_id=", scroll_id)
for(i in 1:100){
    req <- GET( url )
    stopifnot(status_code(req) == 200)
}
```

![screen shot 2015-03-03 at 22 29 36](https://cloud.githubusercontent.com/assets/5968486/6474074/b4779ea6-c1f5-11e4-866c-df5a2449808e.png)
![screen shot 2015-03-03 at 22 31 47](https://cloud.githubusercontent.com/assets/5968486/6474075/b49597d0-c1f5-11e4-8c2c-0dc516ff3348.png)

**Comment by jeroenooms** [comment]
Okay so it looks good, right? Before and after are very similar.

**Comment by pgrosu** [comment]
@ucbpaio, so for-loops in R are notorious for using a lot of memory, which you might already know.  Does the following code also seem to use a lot of memory for you as well?

```
url <- paste0("http://localhost:9200/_search/scroll?scroll=1m&scroll_id=", scroll_id)

get.fun <- function(n) {
    req <- GET( url )
    stopifnot(status_code(req) == 200)
}
 
apply( matrix(1:100), 1, get.fun)
```

**Comment by jeroenooms** [comment]
You might also want to call `gc()` at the end to clean up.

**Comment by ucbpaio** [comment]
@jeroenooms Yes, looks like a great improvement :-)

I thought garbage collections was automatic - gets triggered when required by R?

**Comment by jeroenooms** [comment]
Yes R does garbage collection automatically once in a while, but it's a bit random when it happens. So when you are benchmarking it can be good to force a garbage collection, to make sure you are comparing both scenarios after gc has done it's job.

**Comment by ucbpaio** [comment]
Thanks for the tip.
