### ISSUE TITLE
GET url encoding issue

### ISSUE THREAD

**Issue by krose** [hadley/httr#204]
I'm trying to get the lat/lon from the Google Geocoding API, but the request fails when the danish local characters are in the address. It seems to be an encoding issue.

If you copy/paste this link directly into your browser you get a valid result: http://maps.googleapis.com/maps/api/geocode/json?address=Søholmen+9,+4500+Denmark

But the code section below doesn't work even though the url is the same before it's parsed into the GET function. It works if I use an address without my local characters. I have saved my R script with UTF-8 encoding.

```
library(httr)
library(jsonlite)
library(stringr)

address <- "Søholmen 9, 4500 Denmark"
# address <- "Kronprinsesse Sofies Vej 6, 2000 Denmark"

base_url <- "http://maps.googleapis.com/maps/api/geocode/json?"

# An address OR components
geo_url <- paste0(base_url, "address=", str_replace_all(address, pattern = " ", replacement = "+"))

# Get the result
# get the content
# Parse the JSON
temp_geo_results <- httr::GET(url = URLencode(URL = geo_url), verbose())
temp_geo_results <- httr::content(temp_geo_results, as = "text")
temp_geo_results <- jsonlite::fromJSON(temp_geo_results)
```
Here's my sessionInfo()
```
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=Danish_Denmark.1252  LC_CTYPE=Danish_Denmark.1252        LC_MONETARY=Danish_Denmark.1252
[4] LC_NUMERIC=C                    LC_TIME=Danish_Denmark.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringr_0.6.2   jsonlite_0.9.10 httr_0.5       

loaded via a namespace (and not attached):
[1] RCurl_1.95-4.3 tools_3.1.2 
```

A solution from my stackoverflow question [here](http://stackoverflow.com/questions/28805981/avoid-url-encoding-in-r) has been to wrap the url in the function `enc2utf8()`.

**Comment by hadley** [comment]
The problem is that you're not taking advantage of httr's automatic encoding:

```R
address <- "Søholmen 9, 4500 Denmark"
base_url <- "http://maps.googleapis.com/maps/api/geocode/json?"
r <- httr::GET(base_url, query = list(address = address))
```

**Comment by krose** [comment]
Thanks for looking at it Hadley.

I still think there's an encoding problem though. If I run your example I get an INVALID_REQUEST:

```
Response [http://maps.googleapis.com/maps/api/geocode/json?address=S%F8holmen%209%2C%204500%20Denmark]
  Date: 2015-05-05 12:39
  Status: 200
  Content-type: application/json; charset=UTF-8
  Size: 55 B
{
   "results" : [],
   "status" : "INVALID_REQUEST"
}
```
But if I wrap the address in enc2utf8 it works:

```
address <- "Søholmen 9, 4500 Denmark"
base_url <- "http://maps.googleapis.com/maps/api/geocode/json?"
r <- httr::GET(base_url, query = list(address = enc2utf8(address)))
r
```
The response when I wrap the address in enc2utf8 is valid:

```
Response [http://maps.googleapis.com/maps/api/geocode/json?address=S%C3%B8holmen%209%2C%204500%20Denmark]
  Date: 2015-05-05 12:44
  Status: 200
  Content-type: application/json; charset=UTF-8
  Size: 1.78 kB
{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "9",
               "short_name" : "9",
               "types" : [ "street_number" ]
            },
            {
...
```
I've run the code on my laptop, workstation and on a colleagues computer and they all return an INVALID_REQUEST if I use the build in encoding but it works if I wrap the address in the enc2utf8 function.

**Comment by hadley** [comment]
I think this will be fixed automatically when I switch to using the curl package instead of RCurl. Should be done by the end of the week.

**Comment by krose** [comment]
OK, thanks. I'll follow up, when the switch to curl is done.

**Comment by krose** [comment]
I just tried to run the code after you have switched to curl. It works now so you can close the issue. Thanks!

**Comment by hadley** [comment]
Awesome :)
