### ISSUE TITLE
 Error in token$sign : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by Ironholds** [hadley/httr#208]
The final bugbear in getting an API client library for Google Drive that can handle *drumroll* file uploads! As requested by you, Hadley ;p

>result <- POST("https://www.googleapis.com/upload/drive/v2/files?uploadType=media", config(token = token, useragent = "driver - https://github.com/Ironholds/driver"), body = upload_file(file_path))
 Error in token$sign : $ operator is invalid for atomic vectors

This only happens with this POST call; other POST/GET/PUT/etc calls work fine, with the same token. So I'm at kind of a loss.

Traceback is:

>8 make_request("post", hu$handle, hu$url, config, body_config(body, 
    encode)) 
7 POST(create_url(parameters), config(token = token, useragent = "driver - https://github.com/Ironholds/driver"), 
    ...) at http_wrappers.R#45
6 driver_post(parameters = "https://www.googleapis.com/upload/drive/v2/files?uploadType=media", 
    token = token, body = upload_file(file_path)) at files.R#241
5 upload_file(file_path) 
4 body_config(body, encode) 
3 perform(handle, writer, method, opts, body) 
2 make_request("post", hu$handle, hu$url, config, body_config(body, 
    encode)) 
1 POST("https://www.googleapis.com/upload/drive/v2/files?uploadType=media", 
    config(token = token, useragent = "driver - https://github.com/Ironholds/driver"), 
    body = upload_file(file_path)) 

(I've saved the token R6 object to a serialised file if it'd help with the debugging)

**Comment by hadley** [comment]
Hmmmm, probably something to do with the special path for POSTs with a file body

**Comment by Ironholds** [comment]
Hurn. The weird thing is it's worked in previous iterations. I'll experiment with, say, explicitly wrapping it in a list()

**Comment by Ironholds** [comment]
Nope: still happening with body = list(upload_file()) and body=list(x = upload_file())

**Comment by Ironholds** [comment]
Hmn; I'm going to grab the source and try to diagnose. Lesse...

**Comment by Ironholds** [comment]
Okay, /that/ bug fixed, and then ran into the darndest thing: CURL squawks if you explicitly assign the upload_file() call prior to POST. WTF? @jeroenooms please do let me know if I can help with your project ;p

(Hadley: we're about to have 0.1 of driver. This was the last blocker :))
