### ISSUE TITLE
oauth listener is hard-wired to listen only on `127.0.0.1`

### ISSUE THREAD

**Issue by cboettig** [hadley/httr#210]
Finally figured out what my problem was in issue #191 (which actually isn't at all related to `use_obb` so I've just closed that issue).  

Your OAuth listener function is hardwired to use `127.0.0.1`.  This is incompatible with how Docker containers work, which expect the host to be `0.0.0.0` so that we can link the 1410 port to the host machine.  (e.g. same thing happens if you run Jekyll inside of a container, you just have to set host to 0.0.0.0).  Most software lets us do this (e.g. no problem in servr etc running in a container), but httr has this hard wired to the `localhost` value of `127.0.0.1`, https://github.com/hadley/httr/blob/e746e973e18504996f3d4916c9f2bba334a85ac8/R/oauth-listener.r#L48.  Think you can change this?

Not sure what the best way to expose an option where we can set this would be (e.g. would it make sense to just add `host = 127.0.0.1` as an optional argument to `oauth1.0_token()` function (and any other functions that lead to a call to `oauth_listener()`)?

Thanks for considering; it would be just awesome to have this fixed. I'd work up a pull request but thought I better check in with you first since I'm not sure how best to get the user interface right here.

**Comment by yutannihilation** [comment]
I've faced the same problem with RStudio Server running inside a vagrant VM. It's awesome if I can change the `host` IP!

**Comment by hadley** [comment]
If I did change this, what would you set the host address to in the individual app settings? If it's not 127.0.0.1, the response won't get re-directed to the right place.

**Comment by cboettig** [comment]
@hadley I've put in a pull request with this feature in PR #211; it sets 127.0.0.1 as the default but just provides a way for a user to change it.
