### ISSUE TITLE
Interactive OAuth2 support in Shiny

### ISSUE THREAD

**Issue by MarkEdmondson1234** [hadley/httr#215]
Hi, thanks for the package, it has made easier a lot of things.

But one application I couldn't use it for: I've been looking at using oauth2.0_token() for authenticating to Google APIs for web clients (not offline).  For this I need a redirect URL that is the web app, which presents the authentication token as a parameter, rather than the offline access via copy-pasting the token.  I'm trying to add support for multi-user authentication Shiny applications of existing packages using httr OAuth2 now (such as googlesheets() ) 

It all works locally fine until I deploy to shinyapps.io.  Then I get the error:

    Error : oauth_listener() needs an interactive environment.

It seems there isn't support for using a web application URL in the Auth callback, instead using a local 127.0.0.1 which shinyapps.io doesn't support (?) .  I tried to put the URL in the httr_oob_default option but that wasn't supported, and the interactive() requirement is in a lot of httr functions. 

Is there a way to specify the application URL that is redirected to after verification? Or an example of Shiny / httr OAuth2 verification?  I'm guessing not yet from some SO answers I've read in the meantime, but it looks its very close by having an option to add your web app URL in the httr options somewhere, something like httr_oauth_redirect_uri 

Yours sincerely,
Mark

**Comment by HarlanH** [comment]
+1 I'm not sure if this is more of a Shiny enhancement or an httr enhancement. I suspect it'd take work on both ends to make this work, but I have a couple of fun use-cases. (E.g., log in to Meetup, and pull data from their API for dataviz of groups you belong to!)

**Comment by hadley** [comment]
It sounds like you want interactive OAuth with user credentials? (i.e. you ask the user to authenticate, not the app). Is that right?

**Comment by MarkEdmondson1234** [comment]
Yep. I have that functionality working with httr via get and post in my shinyga package, but would prefer to use httr's OAuth functions as that's what others are using (such as googlesheets package). 





On Tue, Apr 28, 2015 at 5:17 AM -0700, "Hadley Wickham" <notifications@github.com> wrote:












It sounds like you want interactive OAuth with user credentials? (i.e. you ask the user to authenticate, not the app). Is that right?

**Comment by hadley** [comment]
@MarkEdmondson1234 to be clear - do you want to authenticate as fixed user, or allow the user of your app to use their own credentials?

**Comment by MarkEdmondson1234** [comment]
Allow the user to use their own credentials

**Comment by HarlanH** [comment]
Same here. 

Poking around, I found this interesting page about options for OAuth in single-page apps like Shiny. Looks like a popup might be a viable option: http://madhatted.com/2014/6/17/authentication-for-single-page-apps

**Comment by hadley** [comment]
@jcheng5 I think we'll need some input from you - is it possible for a shiny app to respond to arbitrary http requests?

**Comment by jcheng5** [comment]
Yes, but not at a predictable URL; once a session is running, you can request a URL handler to be registered, and Shiny will give you back the actual URL it was registered under.

```r
shinyServer(function(input, output, session) {
  handlerFunc <- function(req, data) {
    # req is a Rook request, and handlerFunc is expected to return a Rook response.
    # Be sure to include a Content-Type header!
    # You can ignore the `data` argument, it's just the list() passed in below.
  }
  url <- session$registerDataObj("oauth_return", list(), handlerFunc)
})
```

There is a (very) little documentation about `registerDataObj` in the `?shiny::session` help topic.

**Comment by jcheng5** [comment]
Rook request/response objects are documented here:
https://github.com/jeffreyhorner/Rook/blob/master/README.md

**Comment by hadley** [comment]
There are relatively few circumstances in which a shiny app will have a consistent IP address that the OAuth2 flow can redirect to. I think this implies you'll need to use the out-of-band (oob) auth in a separate window.

**Comment by jennybc** [comment]
@jzhaoo you should follow this thread… Like @MarkEdmondson1234, I'm interested in getting this to work with, e.g., googlesheets.

**Comment by MarkEdmondson1234** [comment]
@hadley not sure if this helps but for the OAuth2 flow I use at the moment, since shiny apps do not change URL when running I use the session object to use that for the return URL in the OAuth dance (or 127.0.0.1:XXXX for local testing).  The user then adds the Shiny app URL to the allowed redirect settings in the Google API console.

       appURL <- reactive({
            if (!is.null(session)) {
                ## build redirect URI
                paste0(session$clientData$url_protocol, "//", session$clientData$url_hostname, 
                    ifelse(session$clientData$url_hostname == "127.0.0.1", 
                      ":", session$clientData$url_pathname), session$clientData$url_port)
            }
        })

Then I put that in the shinygaGetTokenURL which has access_type=web from https://github.com/MarkEdmondson1234/shinyga/blob/master/R/shinyga_auth.R

    shinygaGetTokenURL <- 
      function(state,         ## state can be anything, used to check return is legit. 
                   client.id     = CLIENT_ID,
                   client.secret = CLIENT_SECRET,
                   redirect.uri  = CLIENT_URL,
                   scope         = c("https://www.googleapis.com/auth/analytics",
                                   "https://www.googleapis.com/auth/analytics.readonly")) {
      
      ## include any scopes for GoogleAPIs
      scopeEnc <- sapply(scope, URLencode, reserved=TRUE)
      scopeEnc <- paste(scopeEnc, sep='', collapse='+')
  
      ## build auth URL
      url <- paste('https://accounts.google.com/o/oauth2/auth?',
               'scope=',scopeEnc,'&',
               'state=',state,'&',
               'redirect_uri=', redirect.uri, '&',
               'response_type=code&',
               'client_id=', client.id, '&',
               'approval_prompt=auto&',
               'access_type=online', sep='', collapse='');
      return(url)
    }

The token is then in the returned URL, accessed via the session object again:

    authReturnCode <- function(session, securityCode){    
  
      pars <- parseQueryString(session$clientData$url_search)
  
      if(length(pars$state) > 0){ 
        ## state can be anything, but used to check return is legit. 
        ## I have a global random string securityCode used per shiny session
        if(pars$state != securityCode){
           warning("securityCode check failed in Authentication! Code:", 
                  pars$state, 
                  " Expected:", 
                   securityCode)
           return()
         } else {
           if(length(pars$code) > 0){
             return(pars$code)
          }
         }
       }
     }

'authReturnCode' is then the token used in API requests.

**Comment by jcheng5** [comment]
It looks like it's OK for OAuth2 to redirect to localhost? And Google doesn't even care what port:
https://developers.google.com/identity/protocols/OAuth2InstalledApp#choosingredirecturi

(I only vaguely remember how OAuth2 works though... I can't get OAuth2 to stick in my brain for more than a day.)

**Comment by hadley** [comment]
@jcheng5 localhost only works with some OAuth2 providers - 127.0.0.1 has worked with every one I've tried.

**Comment by MarkEdmondson1234** [comment]
Jenny now has an example of this working in googlesheets() with httr using modify_url which is the example I was looking for, nice: https://github.com/jennybc/googlesheets/blob/master/R/gs_webapp.R

**Comment by MarkEdmondson1234** [comment]
I have this working as I like it now, in this package:
https://github.com/MarkEdmondson1234/googleAuthR
