### ISSUE TITLE
Allow httr to run without interactive mode 

### ISSUE THREAD

**Issue by adtrombley** [hadley/httr#218]
I can't automate Rscript.exe in a batch file to run this script as it gives me the warning: oath_listener() needs an interactive environment execution terminated

require(RODBC)
require(RSQLite)
require(RGoogleAnalytics)
require(httpuv)
require(httr)

client.secret <- "xxx"
client.id <- "xxx.apps.googleusercontent.com"

token <- Auth(client.id,client.secret)
save(token,file="./token_file")
ValidateToken(token)

**Comment by hadley** [comment]
You either need to run it interactively once and cache the credentials when it asks, or you need to use a OAuth server flow.
