### ISSUE TITLE
GET(handle = ...) doesn't play well with config options

### ISSUE THREAD

**Issue by antoine-lizee** [hadley/httr#219]
It might have been said already, but since it's not mentionned in the doc anywhere, I'm throwing it here:

All the following works:
```R
ggUrl <- "http://google.com"
GET(ggUrl, add_headers("X-FooBar" = "YO: 65445665445rety"))
GET(ggUrl, path =  "/search?q=foobar", add_headers("X-FooBar" = "YO: 65445665445rety"))
GG <- handle(ggUrl)
GET(handle = GG)
GET(handle = GG, path =  "/search?q=foobar")
```
    
But these wouldn't, with very weird error message:
```R
GET(handle = GG, add_headers("X-FooBar" = "YO: 65445665445rety")) 
# Error: is.character(url) is not TRUE

GET(handle = GG, path =  "/search?q=foobar", add_headers("X-FooBar" = "YO: 65445665445rety"))
# Error in function (type, msg, asError = TRUE)  : 
# Could not resolve host: YO

GET(handle = GG, path =  "/search?q=foobar", timeout(10))
#Error in function (type, msg, asError = TRUE)  : 
#Failed connect to :80; Connection refused

#etc...
```

I noticed this kind of behaviour with many configs, (I've not tested them all yet)

I don't think it's appropriate to fix the behaviour, but having a notice somewhere in the doc would be helpful (in the ACTION() docs for instance + the README.md of the repo ?)

**Comment by hadley** [comment]
It's an unfortunate consequence of how argument matching works in R and how I set GET etc up. You can work around it with explicit `config = c(...)`, but I agree that it needs to be documented.

**Comment by hadley** [comment]
Hmmmm, now I'm not sure where this should be documented, since it's just the way named argument matching works in R.   Most people don't httr with a handle (since httr automatically manages a connection pool for you), so it's not a common problem.

**Comment by antoine-lizee** [comment]
I agree/understand this is the way R dispatch works. Nevertheless, you're adding some nice ways of interacting with your API by circumventing the baseline use of R (as usual :-) ) through the passing of functions to the requests methods. It's harder to predict that it would be a problem, so I'm still in favor of adding a Note in the doc of the handle() function. I was actively looking for something like that.

I'd be happy to do it.

**Comment by hadley** [comment]
I'd be happy to review a pull request, but give it a few days because I'm thinking about switching the order of `...` and `config()` to avoid this problem.

**Comment by antoine-lizee** [comment]
Done. I also submitted another small PR (#227) to include all verbs in the http methods family.
