### ISSUE TITLE
More recent version of cacert.pem (2015-04-29)

### ISSUE THREAD

**Issue by wibeasley** [hadley/httr#220]
(*Similar to #114, #154, & #207*)
A new version was released a few days ago: http://curl.haxx.se/docs/caextract.html

https://github.com/hadley/httr/blob/master/inst/cacert.pem

**Comment by hadley** [comment]
I don't think this will work because of the note about "RSA-1024" on http://curl.haxx.se/docs/caextract.html - I'm pretty sure httr uses OpenSSL on windows (and this update causes problems for me on some sites). 

@jeroenooms do you happen to know anything about this?

**Comment by jeroenooms** [comment]
I have not run into this myself, but from the [blog post](https://blog.mozilla.org/security/2014/09/08/phasing-out-certificates-with-1024-bit-rsa-keys/) it understand that this only concerns very old certificates. Websites still using 1024bit will also fail validation in recent versions of Firefox (and perhaps [other browsers](http://www.entrust.com/root-certificates-1024-bit-rsa-keys-removed/)). As this was introduced 8 months ago, I guess that most websites that were still using 1024 will have upgraded their certificates by now. I think it should be fine.

**Comment by wibeasley** [comment]
FWIW, none of my package's users have had problems with the last two CA updates (that httr's missed).  But then again, the audiences are totally different.  [`REDCapR`](https://github.com/OuhscBbmc/REDCapR) is used by (at most) a few dozen clinical researchers calling servers patched & updated by campus IT depts.  `httr` users are a lot more numerous and heterogeneous.

I don't have a stake in this decision, because `REDCapR` uses CA updates [internal to the package](https://github.com/OuhscBbmc/REDCapR/tree/master/inst/ssl_certs), not `httr`'s. 

How about `httr` by default always uses the most recent certificates, but allows users to specify their own if they need to be less secure?  I wouldn't mind writing a short vignette or something that describes how they can revert back to [the older ca-bundle from github](https://github.com/bagder/ca-bundle/blob/e9175fec5d0c4d42de24ed6d84a06d504d5e5a09/ca-bundle.crt) that you linked to on curl.haxx.se.

**Comment by jeroenooms** [comment]
That is a lot of effort to support something that is basically obsolete. Users that really need to connect with via RSA1024 can just disable SSL validation all together. There is not much point in validating an encryption method that is no longer considered secure.

**Comment by hadley** [comment]
There's more to it than that.  If I apply the most recent ca-cert bundle, `GET("https://tcga-data.nci.nih.gov")` fails, but I don't see any problems when I inspect the certificate in safari.  If safari can load it without warnings, I think it's reasonable that httr should too.

**Comment by wibeasley** [comment]
I'm out of my (already limited) area of expertise. But this may not be related to the 1024vs2048 issue.  It looks like this is a 2048 bit certificate.

![image](https://cloud.githubusercontent.com/assets/1372890/7464164/169167f0-f286-11e4-970d-b64b40df9f88.png)

**Comment by hadley** [comment]
I'm going to close this - I can't be bothered digging into exactly why the new certs fail, and post #213, we'll be relying on the certs bundled with R.
