### ISSUE TITLE
bug with new stringr release? wildcard does not match \n

### ISSUE THREAD

**Issue by Tabbob** [hadley/httr#224]
The R-package stringr behaves differently between R-Version 3.1.1 and 3.2.0 (verified on two different machines). Under 3.2.0 the wildcard does not match \n

simplified example:
x <- "abc\n23"

in version R-3.1.1
str_extract_all(x, "a.+?[[:digit:]]{2}")
[1] "abc\n23"        

in version R-3.2.0
str_extract_all(x, "a.+?[[:digit:]]{2}")
[[1]]
character(0)

**Comment by hadley** [comment]
Did you mean to file this in the httr repo?

**Comment by Tabbob** [comment]
Sorry; i pasted it into hadley/stringr
