### ISSUE TITLE
parse_text only returns first character of response content

### ISSUE THREAD

**Issue by jrowen** [hadley/httr#241]
I'm attempting to capture the content of the API response below but am only seeing the first letter of the message.
```
<html>
  <head>
    <style type="text/css"></style>
  </head>
  <body>
    USAGE LIMIT: Hourly usage limit of 100 actions reached. You may resume use of this service at 2015-06-09T05:32:56Z.
  </body>
</html>
```
Here's the method I'm using.  It appears that `readBin`, which is used by `parse_text`, by default only returns the first character, which is why I'm seeing a single letter.
```
r <- GET(...)
> content(r, "text")
[1] "U"
> httr:::parse_text(r$content, "text/html")
[1] "U"
> paste0(readBin(r$content, character(), n=1000), collapse="")
[1] "USAGE LIMIT: Hourly usage limit of 100 actions reached. You may resume use of this service at 2015-06-09T05:32:56Z."
```
Here's the raw content.  If there is a better approach, please let me know.
```
> dput(r$content)
as.raw(c(0x55, 0x00, 0x53, 0x00, 0x41, 0x00, 0x47, 0x00, 0x45, 
0x00, 0x20, 0x00, 0x4c, 0x00, 0x49, 0x00, 0x4d, 0x00, 0x49, 0x00, 
0x54, 0x00, 0x3a, 0x00, 0x20, 0x00, 0x48, 0x00, 0x6f, 0x00, 0x75, 
0x00, 0x72, 0x00, 0x6c, 0x00, 0x79, 0x00, 0x20, 0x00, 0x75, 0x00, 
0x73, 0x00, 0x61, 0x00, 0x67, 0x00, 0x65, 0x00, 0x20, 0x00, 0x6c, 
0x00, 0x69, 0x00, 0x6d, 0x00, 0x69, 0x00, 0x74, 0x00, 0x20, 0x00, 
0x6f, 0x00, 0x66, 0x00, 0x20, 0x00, 0x31, 0x00, 0x30, 0x00, 0x30, 
0x00, 0x20, 0x00, 0x61, 0x00, 0x63, 0x00, 0x74, 0x00, 0x69, 0x00, 
0x6f, 0x00, 0x6e, 0x00, 0x73, 0x00, 0x20, 0x00, 0x72, 0x00, 0x65, 
0x00, 0x61, 0x00, 0x63, 0x00, 0x68, 0x00, 0x65, 0x00, 0x64, 0x00, 
0x2e, 0x00, 0x20, 0x00, 0x59, 0x00, 0x6f, 0x00, 0x75, 0x00, 0x20, 
0x00, 0x6d, 0x00, 0x61, 0x00, 0x79, 0x00, 0x20, 0x00, 0x72, 0x00, 
0x65, 0x00, 0x73, 0x00, 0x75, 0x00, 0x6d, 0x00, 0x65, 0x00, 0x20, 
0x00, 0x75, 0x00, 0x73, 0x00, 0x65, 0x00, 0x20, 0x00, 0x6f, 0x00, 
0x66, 0x00, 0x20, 0x00, 0x74, 0x00, 0x68, 0x00, 0x69, 0x00, 0x73, 
0x00, 0x20, 0x00, 0x73, 0x00, 0x65, 0x00, 0x72, 0x00, 0x76, 0x00, 
0x69, 0x00, 0x63, 0x00, 0x65, 0x00, 0x20, 0x00, 0x61, 0x00, 0x74, 
0x00, 0x20, 0x00, 0x32, 0x00, 0x30, 0x00, 0x31, 0x00, 0x35, 0x00, 
0x2d, 0x00, 0x30, 0x00, 0x36, 0x00, 0x2d, 0x00, 0x30, 0x00, 0x39, 
0x00, 0x54, 0x00, 0x30, 0x00, 0x35, 0x00, 0x3a, 0x00, 0x33, 0x00, 
0x32, 0x00, 0x3a, 0x00, 0x35, 0x00, 0x36, 0x00, 0x5a, 0x00, 0x2e, 
0x00))
```

**Comment by jeroenooms** [comment]
The problem is that your data is not text. It contains `\0` values (`0x00`) which mark the end of a text string.

**Comment by jrowen** [comment]
Here's a URL that will work ([spec](http://comtrade.un.org/data/Doc/API)).  You'll need to run 100 requests in less than an hour before you'll see the error message.
```
http://comtrade.un.org/api/get?max=500&type=C&freq=A&px=HS&ps=2014&r=842&p=826&rg=2&cc=TOTAL
```
Here is the original message I encountered.
```
> r <- GET("http://comtrade.un.org/api/get", query = params)
> content(r)
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p>U</p></body></html>
 
Warning message:
XML content does not seem to be XML: 'U' 
```
The default response is json, so it would be ideal if the server also returned this message as json (I've filed a request).

**Comment by jeroenooms** [comment]
You should always check `stop_for_status(r)` before calling `content(r)`

**Comment by jeroenooms** [comment]
But you're right that this server returns borked error responses. But if you call `stop_for_status` before calling `content` it should not be a problem.

**Comment by hadley** [comment]
Is that UTF-16 maybe?

**Comment by jrowen** [comment]
It doesn't appear to be UFT-16.
```
> content(r, encoding = "UTF-16")
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p>NA</p></body></html>
 
Warning message:
XML content does not seem to be XML: 'NA'
```
Thanks for the `stop_for_status` suggestion--I'll add it.  For this response, it would seem that the only way to capture the error message is to use the customized `readBin` call in my first post.

**Comment by jeroenooms** [comment]
@hadley I don't think so, if I interpret it as utf-16 chineese text comes out (literally). The problem can quite easily be reproduced by performing 2 requests quickly one after another because the server also has a one-per-second rate limit:

```r
library(httr)
url <- "http://comtrade.un.org/api/get?max=500&type=C&freq=A&px=HS&ps=2014&r=842&p=826&rg=2&cc=TOTAL"
req1 <- GET(url)
req2 <- GET(url)
bin <- req2$content

# The actual message:
rawToChar(bin[seq(1, length(bin), 2)])

# As UTF16
library(stringi)
stri_encode(bin, "UTF-16")
```

**Comment by gagolews** [comment]
With high probability this is UTF-16:

```
> stri_enc_isutf16le(bin)
[1] TRUE
```

Fetch binary data and use `stringi::stri_encode()` for that. 
But beware: there are 2 UTF-16 variants: Little (LE) and Big (BE) endian. This stream is `UTF-16LE`.:

```
> stri_encode(bin, "UTF-16LE")
[1] "RATE LIMIT: You must wait 1 seconds."
```

**Comment by gagolews** [comment]
" If the BOM is missing, RFC 2781 says that big-endian encoding should be assumed." -- that's why the `UTF-16` converter alias is mapped to `UTF-16BE` in ICU by default

**Comment by jeroenooms** [comment]
Nice catch! Second time this week endianness bites me. Anyway @jrowen you should warn these guys that their server should either declare utf-16 in the content-type response header, or just return utf-8 like everyone else.

**Comment by gagolews** [comment]
... or add BOMs

**Comment by jeroenooms** [comment]
![solved](http://www.quickmeme.com/img/40/40c674c88606b351e6b0df07a4bfc734e7c1326b97eb7ee502d6304a6523b5a3.jpg)

**Comment by jrowen** [comment]
Thanks to everyone for taking a look at this.
