### ISSUE TITLE
VERB for POST

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/httr#242]
Maybe this is just my misunderstanding, but the docs of `VERB` says that it is for an _arbitrary verb_. Does that mean that it is supposed to work with `POST`? Because it does not.

This is OK:

```r
> POST(url = "http://httpbin.org/post")
Response [http://httpbin.org/post]
  Date: 2015-06-09 23:04
  Status: 200
  Content-Type: application/json
  Size: 380 B
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "application/json, text/xml, application/xml, */*", 
    "Accept-Encoding": "gzip", 
    "Content-Length": "0", 
    "Host": "httpbin.org", 
...
```

But this is not:

```r
> VERB("POST", url = "http://httpbin.org/post")
Response [http://httpbin.org/post]
  Date: 2015-06-09 23:04
  Status: 405
  Content-Type: text/html
  Size: 178 B
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

Seemingly `httr` is not sending a `POST` request, but a `GET`.

**Comment by hadley** [comment]
The problem is this line: https://github.com/hadley/httr/blob/master/R/request.R#L103-L105

I think it may be an artefact of RCurl, because when I remove it in the dev version, all the unit tests continue to work

**Comment by gaborcsardi** [comment]
Hmmm, this does not seem to fix the issue above, I still get a 405 with `VERB`.

**Comment by hadley** [comment]
Oh I guess I didn't actually test that the request worked :/

**Comment by hadley** [comment]
POST is challenging because it usually requires a body and sometimes curl changes the request method in order to be "helpful"

**Comment by gaborcsardi** [comment]
I see. I usually do have a body, only left it out for simplicity. But it does not work with a body, either:

```r
> VERB("POST", url = "http://httpbin.org/post", body="foobar")
Response [http://httpbin.org/post]
  Date: 2015-06-10 18:00
  Status: 405
  Content-Type: text/html
  Size: 178 B
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>

```

**Comment by hadley** [comment]
Yeah, body isn't plumbed up, so that won't help either :/

**Comment by gaborcsardi** [comment]
Anyway, this is nothing major, I can work around it easily. Maybe it is worth mentioning in the docs that `VERB("POST", ...` does not work, though.
