### ISSUE TITLE
missing window.setTimeout as option in PUT or submit_form functions

### ISSUE THREAD

**Issue by yonicd** [hadley/httr#244]
i am filling a form using httr::submit_form and I can not make the function wait until the webpage has loaded like in javascript window.setTimeout

    url <- "https://url.retail.publishedprices.co.il/login"
    pg.session <- html_session(url,ssl.verifyhost = 0L, ssl.verifypeer = 0L)
    pg.form <- html_form(html(pg.session))
    filled_form <- set_values(pg.form[[1]],
                      username = "DorAlon",
                      password = "")
    body(submit_form)[[3]]<-quote(url <- XML::getRelativeURL(form$url, session$url))
    out <- submit_form(session = pg.session, filled_form)
    html(out)%>%html_nodes("#fileList")%>%html_table()
    [[1]]
    [1] Name Type Size Date     
    <0 rows> (or 0-length row.names)

where the actual table (#fileList) is full of data but takes ~2000ms to load. submit_form should be the place to put in the window function but i cant find anything that fits in httr_options() to put in config=list()

**Comment by hadley** [comment]
`html_session()` always downloads the complete html page.

**Comment by yonicd** [comment]
the submit_form runs too fast and doesnt let the page load.

can i run html_session instead of form_submit? 
when i have a form i filled out (filled_form) and am entering into the site submit_form(session=pg.sesson, filled_form)? 
after the form is filled it opens a new page where data is loading.

**Comment by hadley** [comment]
I think you misunderstand how rvest works - it just retrieves the html of the page. It doesn't execute js. You may need a tool like rselenium.

**Comment by yonicd** [comment]
sorry to keep on, but i ran the verbose=T of submit_form you switch from GET to POST at once. wouldnt inserting Sys.sleep(time) between them allow for the page to load any dynamic content like it does in js code?

**Comment by hadley** [comment]
No. Rvest does not execute js.
