### ISSUE TITLE
Unable to install on Windows/x86/something?

### ISSUE THREAD

**Issue by Ironholds** [hadley/httr#245]
devtools::install_github("hadley/httr"):

>Error : package 'httr' is not installed for 'arch = i386'
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Program Files/R/R-3.2.0/library/httr'
* restoring previous 'C:/Program Files/R/R-3.2.0/library/httr'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Program Files\R\R-3.2.0\library\00LOCK-hadley-httr-2a5bec2\httr\libs\x64\httr.dll to C:\Program Files\R\R-3.2.0\library\httr\libs\x64\httr.dll: Permission denied
Error: Command failed (1)

I distinctly installed curl from CRAN to make sure that it isn't an issue with the compiled code, and that went off without a hitch. So I'm not sure what's going on.

**Comment by jeroenooms** [comment]
I think the problem is that devtools depends on httr so it cannot be unloaded? Can you try to install using R CMD INSTALL?

**Comment by Ironholds** [comment]
Done and works! Thankee :)
