### ISSUE TITLE
is there a reason XML isn't imported? 

### ISSUE THREAD

**Issue by jread-usgs** [hadley/httr#246]
XML is suggested but not imported, but used to deal with responses similar to how jsonlite is used. We use httr in a package and results are a bit unexpected when users don't have XML installed already: https://travis-ci.org/USGS-R/sbtools/builds/66867167#L2710

we are fine importing XML in our httr dependent packages if this is a wontfix on your end.

**Comment by hadley** [comment]
Have you read the note in `content()`?

**Comment by jread-usgs** [comment]
Ok, I see now. sorry for missing that.

**Comment by hadley** [comment]
And I'll be switching to xml2 soon anyway.
