### ISSUE TITLE
PKI.load.key can't open google json keys

### ISSUE THREAD

**Issue by mlgrm** [hadley/httr#247]
httr uses PKI to load rsa private keys, but doesn't like the way google formats them:
```
> secrets <- fromJSON("data/xxx-4490e3ab8b82.json")
> tok2 <-oauth_service_token(oauth_endpoints("google"),secrets,"https://spreadsheets.google.com/feeds")
Error in PKI::PKI.load.key(textConnection(private_key), private = TRUE) : 
  cannot find RSA private key in PEM format
```
if you reform the key to match `PKI.save.key`'s format you get an ssl error for a malformed key.
```
> secrets$private_key <- gsub("PRIVATE KEY", "RSA PRIVATE KEY", secrets$private_key)
> tok2 <- oauth_service_token(oauth_endpoints("google"),secrets,"https://spreadsheets.google.com/feeds")
Error in PKI::PKI.load.key(textConnection(private_key), private = TRUE) : 
  error:0D0680A8:lib(13):func(104):reason(168)
```
is this really a `PKI` problem or is it a google credentials problem?

(oddly, sometimes the reason code is 58, though it's usually 168)

**Comment by hadley** [comment]
Are you using the dev version of PKI?

**Comment by mlgrm** [comment]
nope.  should i be?

**Comment by hadley** [comment]
The `s-u` one - can you file a bug there with the problem you're seeing?

**Comment by mlgrm** [comment]
will do.  thanks.

**Comment by mlgrm** [comment]
doesn't look like there's been much activity there in a while...

**Comment by mlgrm** [comment]
actually, they got back right quick.  it looks like the dev version of PKI also requires libssl-dev. (doh!)  but now we're back to the original problem with not being able to read the private key, as above.

**Comment by mlgrm** [comment]
looking at s-u's response (s-u/PKI#15), i'm wondering if i'm doing something wrong with the google credentials.  is the file produced by "generate json key" in the oauth bit of the credentials page in the developers' console not what was referred to in the `oauth_service_token` examples?

**Comment by hadley** [comment]
Maybe this is now fixed since the dev version uses @jeroenooms' openssl package?

**Comment by hadley** [comment]
Please re-open if it doesn't

**Comment by jeroenooms** [comment]
@mlgrm could you give an example of what the `xxx-4490e3ab8b82.json` looks like?
