### ISSUE TITLE
Error: "too many open files" when using httr::GET to download a list of url

### ISSUE THREAD

**Issue by mickeylzj** [hadley/httr#248]
When I use `httr::GET` to download a list of URLs, it crashes at the 1017th URL
Error message:
Cannot open file /home/username/R/x86_64-pc-linux-gnu-library/3.1/httr/Meta/package.rds
Too many open files

Maybe a bug in httr?

**Comment by jeroenooms** [comment]
Can you please include which versions of R, httr and curl that you are using. Make sure you test that the problem still appears in the latest version and has not already bee fixed.
