### ISSUE TITLE
How to use oauth under proxy server.

### ISSUE THREAD

**Issue by brenoea** [hadley/httr#251]
There is any way I can use oauth2.0_token()  through a proxy server, like  use_proxy() function?

**Comment by jennybc** [comment]
@brenoea Can you describe what failure looks like if you try to use `httr::oauth2.0_token()` right now with a proxy server? I have someone struggling to authorize `googlesheets` but I've had him try with another `httr`-using package ([`rdrop2`](https://github.com/karthik/rdrop2)) and he gets the same error. So it's not specific to `googlesheets` or Google auth. I wonder if it is this .... I've been able to elicit this description of his internet access: 'Windows computer linked to a server running Unix".

**Comment by hadley** [comment]
You should be able to use `use_proxy()` together with OAuth. I'll reopen someone can provide a reproducible failure.
