### ISSUE TITLE
[feature-request] Streaming uploads for large files

### ISSUE THREAD

**Issue by zachmayer** [hadley/httr#258]
The [requests library for python](http://docs.python-requests.org/en/latest/user/advanced/) supports streaming uploads for large files, which is pretty cool:

> Requests supports streaming uploads, which allow you to send large streams or files without reading them into memory. To stream and upload, simply provide a file-like object for your body:

```{python}
with open('massive-body', 'rb') as f:
    requests.post('http://some.url/streamed', data=f)
```

It would be really cool if httr supported something similar.  It would be really cool to stream a file in from one api, process the stream in R, and then stream it back out to another api.

**Comment by jeroenooms** [comment]
Both the `body = upload_file(filename))` as well as uploading a file as part of a multipart form post [do exactly this](https://github.com/hadley/httr/blob/master/R/body.R#L18-L23).
