### ISSUE TITLE
Document how to use a different SSL cert file

### ISSUE THREAD

**Issue by wibeasley** [hadley/httr#263]
(Related to #262, but reduces the potential for abuse.)

How about an example where a new crt file is used?
```r
#' @examples
#' \dontrun{
#' result <- httr::POST(
#'   url    = "http://httpbin.org/post",
#'   body   = "A simple text string", 
#'   config = httr::config(cainfo = "./ssl_certs/mozilla_ca_root.crt")
#' )
#' }
```

I think there are only two examples in the reference manual where `config` is set through a local call.  Neither one of them use named parameters (just its position).  I think this example in `POST()` could fill a gap.

If either of you like the example, I'll create a pull request.

**Comment by hadley** [comment]
I just don't think these are important enough to include in the main examples.
