### ISSUE TITLE
Sign API Requests with Credentials using httr

### ISSUE THREAD

**Issue by ankurbhatia28** [hadley/httr#265]
I'm trying to use Hackpad's API in R. Unlike the example in [httr](https://github.com/hadley/httr/blob/master/demo/oauth2-github.r), the [Hackpad documentation](https://hackpad.com/Hackpad-API-v1.0-k9bpcEeOo2Q)  
1. uses oauth 1.0 and  
2. says that the requests should be signed with your credentials. 

I do not completely understand how to do the 2nd part in R (with any library). I understand how to use the request, authorize, and access URLs -- but those are not provided for Hackpad. Instead, the documentation states:  

> Requests must be signed using OAuth 1.0a, using either query parameters or the Authorization header. Users should use their API key / secret as the consumer key without any token ("0-legged OAuth"). 

Here is what I tried in R (to no success):

    library(httr)
    myapp <- oauth_app("hackpad",
                   key = mykey,
                   secret = mysecret)
    hackpad_token <- oauth1.0_token(oauth_endpoint(authorize = 'https://hackpad.com/api/1.0/',
                                               request = 'https://hackpad.com/api/1.0/',
                                               access = 'https://hackpad.com/api/1.0/'),
                                myapp)

and also

    req <- GET("https://hackpad.com/api/1.0/pad/k9bpcEeOo2Q/content/latest.html",
           config = authenticate(user=myuser,
                                 password=mypass))

which tries to return the API documentation content.

Not sure if there is a way to do this using httr, would appreciate any advice. Thanks

**Comment by hadley** [comment]
Hmmm, this is a bizarre auth scheme. You have to create a Token subclass to handle it:

```R
library(httr)

TokenZeroLeg <- R6::R6Class("TokenZeroLeg", inherit = Token, list(
  init_credentials = function() {},
  sign = function(method, url) {
    oauth <- oauth_signature(url, method, self$app, NULL, "")
    
    c(httr:::request(url = url), oauth_header(oauth))
  }
))

oauth_zero_leg_token <- function(app) {
  TokenZeroLeg$new(
    app = app, 
    endpoint = NULL,
    credentials = list(),
    cache_path = FALSE
  )
}

hackpad <- oauth_app("hackpad", "Ahtj5h64B7Q")
hackpad_token <- oauth_zero_leg_token(hackpad)

req <- GET("https://hackpad.com/api/1.0/pads/all", config(token = hackpad_token))
content(req)
```
