### ISSUE TITLE
Error in curl

### ISSUE THREAD

**Issue by maryambagheri** [hadley/httr#266]
I try to setup a twitter oauth, but I get the following error:
> setup_twitter_oauth(api_key,api_secret)
[1] "Using browser based authentication"
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
could you please help me?

**Comment by maryambagheri** [comment]
I also get this too:

 setup_twitter_oauth(api_key,api_secret,access_token,access_token_secret)
[1] "Using direct authentication"
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'

**Comment by hadley** [comment]
It's likely to be a proxy problem. But I'm not sure why you're filing this bug here. `setup_twitter_oauth()` isn't an httr function.
