### ISSUE TITLE
httr 1.0.0 does not work with R 3.0.2 while the requirement for R in DESCRIPTION file is R (>= 3.0.0)

### ISSUE THREAD

**Issue by nhanitvn** [hadley/httr#267]
I get an error running the code in R 3.0.2.
```
> library(httr)
> b2 <- "http://httpbin.org/post"
> POST(b2, body = "A simple text string")
Error in handle_setopt(h, ...) : could not find function "anyNA"
```
It turns out that R 3.0.2 does not have the "anyNA" function. That function is available from R 3.1.0 only (http://www.r-statistics.com/2014/04/r-3-1-0-is-released/). Should we update the DESCRIPTION file to force the R version to be >= 3.1.0 OR update the code to support versions older than 3.1.0?

**Comment by jeroenooms** [comment]
This has been fixed already: https://github.com/jeroenooms/curl/commit/5e380375a8e9e69d7c36a91bf3a1a651d1e6a82b

**Comment by nhanitvn** [comment]
Kool, thanks.
