### ISSUE TITLE
readfunction nbytes parameteres

### ISSUE THREAD

**Issue by tengfei** [hadley/httr#269]
httr is a very nice package, thanks a lot! and I am newbie for restful : ) one question, for a multipart upload, can I specify this parameter somewhere?

for AWS multipart, it return a uri for each single part, and in request python package, it is something like

```python
f = open(file, 'rb')
requests.put(uri,data=f)
```

I directly connect the f to data, then it works

but somehow in R with httr

```R
PUT(uri, body = upload_data(file)) 
```
doesn't work. 

But if I use something like this

```R
con = file(file, 'rb)
b = readBin(con, "raw", part_size)
PUT(uri, body = b)
rm(b)
```

in a loop, it actually works. I am controling the part_size myself. 

It will be nice if I could do this automatically like python request style? every time I just do PUT(uri, body  = con) with new uri, it will just put chunk by chunk?

thanks again!

**Comment by hadley** [comment]
This should work automatically already. Could you please make a reproducible example?
