### ISSUE TITLE
How does httr OAuth2 handle multiple Shiny connections?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [hadley/httr#270]
I would like to have a Shiny package that enables multiple users authenticating their own sessions in Google OAuth2.

I have the package working with this [Shiny app here](https://mark.shinyapps.io/searchConsoleRDemo) downloading data from the Google search console.

The problem is that if one user authenticates, and then another user whilst the first is still in session, the first user's API calls are bearing the second's auth token and so errors, 403.  You can test it using two different browser and two logins. I get this error reported back:

    JSON fetch error: User does not have sufficient permission for site 'http://example.com/'. 
    See also: https://support.google.com/webmasters/answer/2451999.

After a lot of re-factoring of the package I'm wondering if the Token2.0 object itself is outside of the shinyServer session environment, and so not respecting the [scoping rules for Shiny?](http://shiny.rstudio.com/articles/scoping.html)  I'm using <<- from within the package to assign to a session parameter in shinyServer(), so I don't see how two users could share any of the same data aside from a global environment somewhere.

The reason I think it may be the R6 object itself is I use httr in another project without using httr's OAuth tokens, and that works as expected.

**Comment by hadley** [comment]
If you're handling multiple users on one machine, you shouldn't rely on httr's default caching (and in fact you should turn it off).  You'll need to figure out how to store and retrieve per user.

**Comment by jennybc** [comment]
Eavesdropping here. @MarkEdmondson1234 -- we should probably go commiserate about this elsewhere.

But I was glad for the link to the Shiny scoping rules, which I confess I had not read. A possible explanation for the the problem given my auth flow: I store the token in an environment private to the `googlesheets` package. But it is loaded via `library(googlesheets)` in `server.R`, outside of `shinyServer()`. Does that mean that this environment is one of the objects visible across all sessions? That could explain the multi-user crosstalk. Maybe we have to adopt @hadley's hashing strategy from the default caching to distinguish the tokens for different users? Or can we somehow force the creation of this internal environment to be per session?

@MarkEdmondson1234 let's discuss further on one the two issues linked above.
