### ISSUE TITLE
GET returns only part of the table from URL

### ISSUE THREAD

**Issue by lateotw** [hadley/httr#272]
I'm using httr to query an internal database with authentication, so unfortunately it cannot be reproduced here, the code I use is: 

queryURL<- "https://someInternalURL"
data <- content(GET(queryURL, authenticate(uid, upw)))
data.df <- readHTMLTable(data, stringsAsFactors=FALSE)

The data.frame returned should contain about 200 rows, however the result I get only contains about 100 rows. I'm able to view the complete report in Chrome browser though. Is there a setting I need to change to query the entire report?

**Comment by hadley** [comment]
Seems more likely to be a `readHTMLTable()` issue than an httr issue.
