### ISSUE TITLE
Cached tokens not being read in non-interactive mode

### ISSUE THREAD

**Issue by DataWookie** [hadley/httr#276]
Hi,

I am using OAuth2.0 authentication to connect to a Google service. Authentication works perfectly when I do it interactively from the prompt. The resulting token has been cached in the .httr-oauth file and on subsequent authentication attempts the token is read back from the cache file.

This is great!

However, I am writing a test suite too and this is where I run into trouble because the authentication seems to refuse to work in a non-interactive environment (which is what you get when you run the test suite under RStudio). I get the error stack below:

    1. Error: OAuth is successful --------------------------------------------------
    oauth_listener() needs an interactive environment.
    1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls)
    2: eval(code, new_test_environment)
    3: eval(expr, envir, enclos)
    4: shortener_authenticate(key, secret) at test-00-google-authentication.R:6
    5: httr::oauth2.0_token(httr::oauth_endpoints("google"), httr::oauth_app("google", key = key, 
           secret = secret), scope = "https://www.googleapis.com/auth/urlshortener", cache = TRUE) at /home/colliera/proj/R-026/R/oauth.R:12
    6: Token2.0$new(app = app, endpoint = endpoint, params = params, cache_path = cache)
    7: public_bind_env$initialize(...)
    8: self$init_credentials()
    9: init_oauth2.0(self$endpoint, self$app, scope = self$params$scope, type = self$params$type, 
           use_oob = self$params$use_oob)
    10: oauth_listener(authorize_url, is_interactive)
    11: stop("oauth_listener() needs an interactive environment.", call. = FALSE)

I have browsed through the code in oauth-token.r but it's not clear to me why it is checking for an interactive environment when the tokens are going to be read from the cache. Surely if we are using cached data then being interactive should not be a requirement?

Thanks for your time considering my question.

Best regards,
Andrew.

**Comment by DataWookie** [comment]
Oh, and for clarity, I am running httr version 1.0.0 on R version 3.1.2.

**Comment by jennybc** [comment]
I have gazed at this error message alot myself, troubleshooting a package of mine and that of someone else. So far the problem has always been that the `.httr-oauth` file is not where it's expected to be. Even when that seems impossible.

What if you add a test that will fail if `.httr-oauth` cannot be found in working directory? That would provide some useful information

Another shot in the dark: once you request your 26th Google auth token, your first falls off the end and won't be valid anymore. Could you have an invalid token in your testing directory and a valid one in whatever working directory is when you're doing interactive development?

**Comment by DataWookie** [comment]
Hi Jenny,

Thanks for the suggestion. I have adapted the test suite to check for the presence of `.httr-auth` in the working directory and, if it's not there, link one in from the project's root directory.

Best regards,
Andrew.
