### ISSUE TITLE
Switch to urltools

### ISSUE THREAD

**Issue by Ironholds** [hadley/httr#279]
I have no idea *what* you want to switch over to urltools (although I imagine it's URL-related) but I was told to file this issue, so I have ;)

**Comment by jeroenooms** [comment]
Ugh, that will drag in Rcpp. Would be nice if httr could work without c++.

**Comment by hadley** [comment]
@jeroenooms why?

**Comment by hadley** [comment]
Hmmm, looking at this now, I'd say it's going to be quite a lot of work for minimal gain (except for parsing speed which I don't think will affect typically httr usage).
