### ISSUE TITLE
whitelist .httr-oauth in RStudio file browser?

### ISSUE THREAD

**Issue by jennybc** [hadley/httr#281]
Do you think the pros of making `.httr-oauth` visible in RStudio outweigh the cons?

I find alot of people are confused about why auth tokens can (or can not) be found and refreshed. This almost always stems from there being no cached token in working directory and so `httr` [wants an interactive environment](http://www.google.com/search?as_oq="oauth_listener()+needs+an+interactive+environment"). If the presence/absence of `.httr-oauth` were a little more visible, maybe that would help?

**Comment by hadley** [comment]
@kevinushey can we do this please?

**Comment by kevinushey** [comment]
I've logged this on the RStudio side so hopefully you'll see it whitelisted soon.

**Comment by jjallaire** [comment]
My concern here is that if it's actually important that this file be visible to end users then perhaps it shouldn't be a dot file in the first place (i.e. what about users that don't use RStudio or go looking for the file with `ls` commands or within the Finder or Windows Explorer). We can certainly "make it work" in RStudio but this might just be masking the underlying problem.

I think the convention of using dotfiles for configuration / metadata is a strong and legit one in very developer-oriented ecosystems, however I'm not sure that this really characterizes the R user community. In short, I'm happy to make this show up the RStudio files pane if you want me to but this seems like this might be too narrow a fix.

**Comment by jennybc** [comment]
There are other examples of R-specific dot files visible in the RStudio files pane: `.Rprofile`, `.Renviron`, `.Rdata`, and `.Rhistory`. I realize `.httr-oauth` has a very different purpose. Does the rationale for revealing those other files apply to it?

**Comment by jjallaire** [comment]
I think the same rationale does apply, however at the same time I think
it's regrettable in the first place that those files are dot files (as they
are harder to locate for non-technical users). I don't think R is served
well by having a convention of configuration being in dotfiles which are
then impossible to see unless you either (a) know how to; or (b) are
running RStudio and happen to have your dotfile de-jour whitelisted in.

Again, I'm happy to add this to the whitelist but I just wanted us to step
back and think about the implications of proliferating dotfile based
configuration / metadata before doing so.

**Comment by hadley** [comment]
@jjallaire in that case, maybe RStudio should should all dot files? (except maybe for a blacklist like `.Rproj.user`?

**Comment by jjallaire** [comment]
There's unfortunately a lot of crud dotfiles (especially in the home
directory) which would be a big distraction for a lot of users.

**Comment by jjallaire** [comment]
FYI made the change here: https://github.com/rstudio/rstudio/commit/0b96efe02a3197a43ca2d2476767a8a5b33753c3
