### ISSUE TITLE
POST returns error for a good DoubleClick API call

### ISSUE THREAD

**Issue by loudoro** [hadley/httr#284]
Hello,

I tried to run a Google DoubleClick API call with the POST function. The call runs fine in Google's API explorer (https://developers.google.com/apis-explorer/#p/doubleclicksearch/v2/doubleclicksearch.reports.request), but returned an error message in R.

I would really appreciate if you could share some insights.

Thanks!

Response [https://www.googleapis.com/doubleclicksearch/v2/reports]
  Date: 2015-10-15 21:43
  Status: 400
  Content-Type: application/json; charset=UTF-8
  Size: 258 B
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "filter[0].values: Expected one filter value but found 0."
   }
  ],
  "code": 400,
...

Request body:
{
  "downloadFormat": "csv",
  "maxRowsPerFile": 6000000,
  "reportType": "keyword",
  "statisticsCurrency": "agency",
  "reportScope": 
  {
    "agencyId": "xxxxx",
    "advertiserId": "xxxxx"
  },
  "timeRange": 
  {
    "startDate": "2015-10-10",
    "endDate": "2015-10-10"
  },
  "columns": 
  [
    {
      "columnName": "keywordId"
    },
    {
      "columnName": "keywordText"
    },
    {
      "columnName": "campaign"
    },
    {
      "columnName": "monthStart"
    },
    {
      "columnName": "cost"
    },
    {
      "platformSource": "FLOODLIGHT",
      "savedColumnName": "xxxxx"
    }
  ],
  "filters": 
  [
    {
      "column": 
      {
        "columnName": "cost"
      },
      "operator": "greaterThan",
      "values": 
      [0
      ]
    }
  ]
}

**Comment by hadley** [comment]
You will need to careful compare what the browser sends vs. what you're doing in R. Use the debugger built in to your browser and `httr::verbose()`
