### ISSUE TITLE
README instructions to update certificate bundle

### ISSUE THREAD

**Issue by ijlyttle** [hadley/httr#290]
Referring to https://github.com/hadley/httr#updating-ca-bundlecrt:

Current instructions say:

```r
GET(
  "https://github.com/bagder/ca-bundle/raw/e9175fec5d0c4d42de24ed6d84a06d504d5e5a09/ca-bundle.crt",
  write_disk("inst/cacert.pem", overwrite = TRUE)
)
```

I could be missing something, but I get the sense that the intention is to operate on the installed package, in which case I would propose:

```r
GET(
  "https://github.com/bagder/ca-bundle/raw/e9175fec5d0c4d42de24ed6d84a06d504d5e5a09/ca-bundle.crt",
  write_disk(system.file("cacert.pem", package = "httr"), overwrite = TRUE)
)
```

Happy to PR, if this is the right thing to do.

**Comment by hadley** [comment]
Those instructions are for me - I probably should make that more clear.

**Comment by ijlyttle** [comment]
That makes sense. 

In that case, I'll just leave this open and leave it to you to address and close.
