### ISSUE TITLE
request_prepare kills POST calls with token

### ISSUE THREAD

**Issue by ReportMort** [hadley/httr#291]
I am receiving the error `Error: is.request(y) is not TRUE` while trying to perform a POST call with an oauth2.0_token. My POST call is very similar to the demos:

```
POST(url=url, config=config(token=my_token), body=this_request_body)
```

I've noticed that `POST()` calls `request_perform()` which calls `request_prepare()`, which checks if there is a token and signs the request. The problem occurs at https://github.com/hadley/httr/blob/f7593b7d5b3f9396469d1220dd4b38206fbb7d2e/R/request.R#L107 when using the `c()` operator to push the request and signed token together. This operation forces a check that `token$sign(req$method, req$url)` is a valid request object, but it's not, so the code bombs. `token$sign(req$method, req$url)` actually returns a list of length 2 containing a url string and a config (which is a valid request by itself). The url seems redundant and I think it will be inherited from the actual `req` object when the `%||%` function runs, so it can really be ignored.

Everything works fine when I peel off the config portion of the `token$sign` operation:
```
req <- c(req, token$sign(req$method, req$url)$config)
```

**Comment by hadley** [comment]
Can you provide a reproducible example? The demos work for me.
