### ISSUE TITLE
trimws forcing R base version 3.2.0 dependency

### ISSUE THREAD

**Issue by ReportMort** [hadley/httr#293]
The function `trimws` was introduced in a recent commit: https://github.com/hadley/httr/commit/7c68198d49ea6b2abb7255c692dddb09fbeaf7b1, specifically at: https://github.com/hadley/httr/blob/7c68198d49ea6b2abb7255c692dddb09fbeaf7b1/R/str.R#L4

The issue is that the DESCRIPTION file states that the package depends on R (>= 3.0.0), but `trimws` wasn't introduced until R package base version 3.2.0, so either `trimws` should be specified explicitly in [str.R](https://github.com/hadley/httr/blob/master/R/str.R) or the DESCRIPTION file should be updated. I think that explicitly including the `trimws` function source code is the better option, in order to be more inclusive of older versions,

**Comment by jeroenooms** [comment]
The `trimws` function was actually introduced in 3.2.0. But still nice to have a version that works with older releases.

**Comment by hadley** [comment]
Fixed in #292
