### ISSUE TITLE
GET('http://abc') gives "object C_stri_detect_regext' not found error

### ISSUE THREAD

**Issue by kkaisurya** [hadley/httr#294]
I am using httr 1.0.0 and when I am trying to just do GET it throws Error in stri_detect_regex(string, patter, opts_regex = attr(pattern: object C_stri_detect_regex' not found. 

When I check in traceback(), before making the stringr dependent call, in httr, it mentions :::pull_off('#(.*)$")

Please let me know any needful that has to be done.

Thanks
Surya

**Comment by jeroenooms** [comment]
Try installing the development version, which does not depend on `stringi`:

```r
devtools::install_github("hadley/httr")
```

**Comment by kkaisurya** [comment]
While I am trying to install the file from master : 

Error in get(Info[i, 1], envir = env) : 
  lazy-load database '/Documents/R/R-3.2.2/library/httr/R/httr.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

Probably the existing httr rdb is corrupt. I tried installing the previous version of httr(0.6.1) and then the master version of httr, it gives following error:

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  object 'vI' not found

**Comment by jeroenooms** [comment]
nah that error just happens when you try to install a package that is currently in use. Restart R and try:

```
install.packages("https://github.com/hadley/httr/archive/master.tar.gz", repos = NULL)
```

**Comment by kkaisurya** [comment]
Sure, Thanks loads. That works. I am trying the GET function in the dev version
