### ISSUE TITLE
Trying to upload a file into teamsite

### ISSUE THREAD

**Issue by kkaisurya** [hadley/httr#295]
I am trying to make an API call to services, convert it into excel and upload it into a Sharepoint teamsite. 
-I have been able to validate and successfully call the API
-I am able to convert the API call into xls/csv as well and stored in a public folder

I am not sure how to upload this file into a specific Sharepoint teamsite. Can I use the httr::upload_file for the same?
Thanks
Surya

**Comment by hadley** [comment]
This question would be more appropriate for stackoverflow.
