### ISSUE TITLE
Documentation on running examples/vignettes with API

### ISSUE THREAD

**Issue by gregmacfarlane** [hadley/httr#296]
The [best practices vignette](https://github.com/hadley/httr/blob/master/vignettes/api-packages.Rmd) has great info on writing a package to use `httr`. 

But there is an unanswered [question on SO](http://stackoverflow.com/questions/29631222/r-code-in-package-vignette-cannot-run-on-cran-for-security-reasons-how-to-manag) about how to handle API calls requiring authorization in a vignette or examples when you submit the package to CRAN. Are there best practices, besides simply setting `eval = F` or supplying a static vignette? Including my own or a throwaway API key seems like a recipe for disaster.

**Comment by jennybc** [comment]
I don't claim this is a best practice! But here's one way to keep your auth-requiring vignette code from running on CRAN, but still easy for you to run. In an setup chunk:

``` r
NOT_CRAN <- identical(tolower(Sys.getenv("NOT_CRAN")), "true")
knitr::opts_chunk$set(purl = NOT_CRAN)
```

And then use `eval = NOT_CRAN` as needed as a chunk option.

**Comment by gregmacfarlane** [comment]
Ooh, that's clever.

**Comment by hadley** [comment]
@jennybc have you used this in a CRAN package that I can point to as reference?

**Comment by jennybc** [comment]
I did this in the googlesheets vignette. But also mistakenly submitted the vignette as built with `NOT_CRAN = FALSE` 😞. What I *meant* to do was build the vignette properly (i.e. with `NOT_CRAN = TRUE` and therefore auth) and send that. I hope to get this right when I update.

**Comment by hadley** [comment]
Won't you get an check error that the included and re-built R code is different?

**Comment by jennybc** [comment]
I don't think so?

Kurt Hornik said: Ideally, only the part of the code which neeks the token would be conditionalized out somehow.  If that is not possible, running the code in the vignettes must be turned off for our checking.

Paraphrasing my follow-up Q + A:

Q: Does CRAN display the built vignette that I submit or the result of CRAN’s attempt to build my vignette?

A: For the web pages, we always use the vignettes as shipped with the package (including the vignette index shipped). CRAN's attempt to build the vignette and run the extracted code is just a quality check.
