### ISSUE TITLE
GET never finishes for url with Umlaut ü

### ISSUE THREAD

**Issue by rentrop** [hadley/httr#297]
`GET` failed to scrape this website

    require(httr)
    GET("http://www.atelco.de/1546/Bügeln.search") # Never finishes
    GET(URLencode("http://www.atelco.de/1546/Bügeln.search")) # works fine

I tried with other websites that have __ü__ in their URL:

    GET("http://www.bosch-home.com/de/produkte/bügeln.html")

My Session-Info is:

    R version 3.2.2 (2015-08-14)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)
    Running under: OS X 10.11.1 (El Capitan)
    
    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] httr_1.0.0
    
    loaded via a namespace (and not attached):
    [1] R6_2.1.1      magrittr_1.5  tools_3.2.2   curl_0.9.4    stringi_1.0-1 stringr_1.0.0 XML_3.98-1.3 

Please update this SO Question: http://stackoverflow.com/questions/34286136/get-never-finishes-for-url-with-umlaut-%C3%BC when this bug is fixed

**Comment by jeroenooms** [comment]
I think this is unrelated to R. Your first example looks like a server issue. The server issues a redirect to the same url and then freezes. Same happens for command line curl:

```
curl -Lv http://www.atelco.de/1546/Bügeln.search
```

The second example works fine for me?

```r
> GET("http://www.bosch-home.com/de/produkte/bügeln.html")
Response [http://www.bosch-home.com/de/produkte/bügeln.html]
  Date: 2015-12-16 12:01
  Status: 200
  Content-Type: text/html; charset=utf-8
  Size: 86.6 kB
<!doctype html>
<html lang="de"><head><!-- MOBIFY - DO NOT ALTER - PASTE IMMEDIATELY AFTER OPENING HEAD TAG --><script type=...
var jsapp = '';
var jsbase = '/de';
var jsbq = 'q';
var jsbs = 'search.html';
var jsbp = '?';
var pID = '463639';
var jsproductStr = 'group=product';
var cookiesAllowed = true;
```

**Comment by hadley** [comment]
@jeroenooms there's definitely a curl buglet there though because you can't ctrl + c to stop the request

**Comment by jeroenooms** [comment]
That's true, but this is a separate issue from escaping of urls: 

 - https://github.com/jeroenooms/curl/issues/25
 - https://github.com/jeroenooms/curl/pull/45
