### ISSUE TITLE
OAuth RSA-SHA1 signatures

### ISSUE THREAD

**Issue by emile** [hadley/httr#307]
[JIRA](https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-oauth-authentication) incoming OAuth1.0 authentication only works with RSA-SHA1 signatures and httr only has HMAC-SHA1 at the moment, making integration difficult. It would be nice if httr knew how to make RSA-SHA1 signatures.

A specialised Token$sign() might be possible but it's far from pretty.

**Comment by jeroenooms** [comment]
The `openssl` package supports creating rsa signatures with `signature_create`:

```r
library(openssl)
msg <- serialize(iris, NULL)
sig <- signature_create(msg, hash = sha1, key = my_key())
signature_verify(msg, sig)
```

**Comment by hadley** [comment]
Again, I'd be willing to review a pull request that implements this, but I'm not going to have time to do it myself. If you can do it in the next week, it can get in the next httr release.
