### ISSUE TITLE
HTTP POST for OAuth1.0 token requests

### ISSUE THREAD

**Issue by emile** [hadley/httr#308]
[RFC5849](http://tools.ietf.org/html/rfc5849#section-2.1) suggests that token requests should be obtained using POST unless the server demands something else. [Core 1.0a](http://oauth.net/core/1.0a/#rfc.section.6.3.1) also recommended POST. httr currently uses GET, which complicates integration with servers that only work with POST (e.g. JIRA).

It would be nice if the endpoint or app configuration could select HTTP methods for obtaining request tokens (and perhaps access tokens).

**Comment by hadley** [comment]
I'd be happy to accept a pull request that implements this
