### ISSUE TITLE
Testing w/ dev version of httr in AppVeyor

### ISSUE THREAD

**Issue by wibeasley** [hadley/httr#319]
The next time httr is updated and you email the reverse dependencies' maintainers, consider giving a few instructions if they're using AppVeyor.  If I understand correctly, the order of `  - travis-tool.sh install_deps` and `  - travis-tool.sh install_github zzzz` [doesn't matter for most packages](https://github.com/search?utf8=%E2%9C%93&q=travis-tool.sh+install_github+appveyor&type=Code&ref=searchresults), but apparently [the order does for  httr](https://github.com/OuhscBbmc/REDCapR/commit/db2efc5efe4bf8da1a13b019063034df8f71951e).  I was getting [403 errors](https://ci.appveyor.com/project/wibeasley/redcapr/build/1.0.178) when I tried to install the GitHub version of httr first.  However the code below worked.  Looking through [`travis-tool.sh`](https://github.com/craigcitro/r-travis/blob/master/scripts/travis-tool.sh), I'm guessing it's related to devtool's dependency on httr?

*Snippet of appveyor.yml*:
```
build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_github hadley/httr
```

I don't know if it's coincidence, but I didn't see any successful use of [`travis-tool.sh install_github hadley/httr`](https://github.com/search?utf8=%E2%9C%93&q=travis-tool.sh+install_github+hadley%2Fhttr&type=Code&ref=searchresults) in `appveyor.yml`.  Regardless, it might be difficult for the revdep maintainers to find working examples.

Tell me if you'd like me to start writing that explanatory paragraph.  It might also help having somewhere permanently in the httr repo.

Thanks again for writing this package.  My life got a lot easier once I switched from RCurl to httr and curl.

**Comment by krlmlr** [comment]
Could the 403 error [you mentioned](https://ci.appveyor.com/project/wibeasley/redcapr/build/1.0.178#L148) be simply the result of GitHub's rate limitation? I don't see why the order should matter, except if the bleeding-edge httr breaks the install_deps function of devtools.

**Comment by wibeasley** [comment]
@krlmlr, you have a much better understanding of these issues than I do, so I'll take your word for it.  I'm happy to try anything that would help diagnose.

@gaborcsardi suggested in https://github.com/krlmlr/r-appveyor/issues/35#issuecomment-171040864 that caching might explain the order dependency.

FWIW, on a Windows 8 machine, devtools_1.9.1 from CRAN installed fine, despite having httr 1.0.0.9000 in the library (and no other httrs in any other library).

**Comment by krlmlr** [comment]
Does install_deps() still work on that Windows 8 machine? (I have no idea why it shouldn't, this is just to be on the safe side.)

**Comment by wibeasley** [comment]
> Does install_deps() still work on that Windows 8 machine? 

Is this what you want me to run from inside the REDCapR project?
```r
Restarting R session...

> devtools::install_deps("REDCapR")
Skipping 2 packages ahead of CRAN: DBI, httr

> devtools::install_deps()
Skipping 2 packages ahead of CRAN: DBI, httr

> sessionInfo()
R version 3.2.3 Patched (2015-12-12 r69765)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] rsconnect_0.3.79 tools_3.2.3      memoise_0.2.1    digest_0.6.9     devtools_1.9.1 
```

I guess if httr is skipped in `install_deps()`, that might explain something.  But I can figure out what, because, devtools still install from CRAN after that:

```r
Restarting R session...

> install.packages("devtools")
Installing package into ‘D:/Projects/RLibraries’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/devtools_1.9.1.zip'
Content type 'application/zip' length 357183 bytes (348 KB)
downloaded 348 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\--redacted--\downloaded_packages
```

**Comment by wibeasley** [comment]
I may have wasted everyone's time.  If so, I'm sorry.  I [switched the order again](https://github.com/OuhscBbmc/REDCapR/commit/426d712ecd84ea05d5db17da8d406b0a966d44b9), and I [didn't get the 403 error](
https://ci.appveyor.com/project/wibeasley/redcapr/build/1.0.186#L149) again.  I guess it was just bad luck or timing with the error happening to coincide with the switching this morning.

I'll run a few more [variations](https://github.com/OuhscBbmc/REDCapR/commit/76fe0d897fd8e52a84fb68e3659c61eb4cd10f4f) to see if the error returns.  Hopefully not.

**Comment by wibeasley** [comment]
It looks like the issue is not related to the yaml file, and instead is network related.  On the most recent try, the [first build/run failed](https://ci.appveyor.com/project/wibeasley/redcapr/build/1.0.188) while the [rebuild/rerun on the same commit passed](https://ci.appveyor.com/project/wibeasley/redcapr/build/1.0.189).  Thirty minutes later, the [re-rerun failed](https://ci.appveyor.com/project/wibeasley/redcapr/build/1.0.190) with the same 403 error message.  5 minutes later, the [4th run failed again](https://ci.appveyor.com/project/wibeasley/redcapr/build/1.0.191).  Then I switched back to the order that has always passed, and [it failed](https://ci.appveyor.com/project/wibeasley/redcapr/build/1.0.192).

I hate networking.  I initially suspected network issues (and reran the build in [178](https://ci.appveyor.com/project/wibeasley/redcapr/build/1.0.178) and [179](https://ci.appveyor.com/project/wibeasley/redcapr/build/1.0.179)), but I thought this morning's correspondence  (between the order and successfully building) had been too tight to be related to anything but the yaml file.  I'll be more persistent next time before raising an issue; I thought I had reasonable evidence.

---------

Related to the original post, it still might be nice to include Travis & AppVeyor instructions/reminders to revdep authors.  But it's less important now that the problem doesn't seem to be specific to httr-vs-devtools.

**Comment by gaborcsardi** [comment]
I think @krlmlr was right and this is because Appveyor is rate limited on GitHub. 

The solution is to create a GitHub token for yourself, it can be read-only, and then set it on Travis as a private `GITHUB_PAT` environment variable. (Technically if it is read-only it does not have to be private, but it is just good to careful.) `GITHUB_PAT` is automatically picked up by `devtools`, which is used internally by r-travis.
