### ISSUE TITLE
UTF-8 warning on `content` call from print.response()

### ISSUE THREAD

**Issue by sckott** [hadley/httr#327]
with `httr v1.1.0` I now get `No encoding supplied: defaulting to UTF-8.` warning when a `response` class prints

```r
#> Response [http://api.crossref.org/journals/0413-6597]
#>   Date: 2016-01-29 00:25
#>   Status: 404
#>   Content-Type: text/plain
#>   Size: 19 B
#> No encoding supplied: defaulting to UTF-8.
```

yet the user can't set encoding for the internal use of `content()` in `print.response()` here https://github.com/hadley/httr/blob/f7593b7d5b3f9396469d1220dd4b38206fbb7d2e/R/response.r#L57  - should this have  `content(x, "text", encoding = "UTF-8")` instead? Or am i missing something

**Comment by jread-usgs** [comment]
:+1:

**Comment by pan0ramic** [comment]
+1

**Comment by steckhan** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
