### ISSUE TITLE
Allow to query the same attribute with multiple items

### ISSUE THREAD

**Issue by nuno-agostinho** [hadley/httr#328]
When trying to query a specific API, I need to pass multiple items to the same attribute.

For example, I need to curl this URL: http://firebrowse.org/api/v1/Metadata/Cohorts?format=json&cohort=ACC,BRCA

If I define a function like this:
```r
queryAPI <- function(format, cohort) {
    query <- list(format = format, cohort = cohort)
    response <- GET("http://firebrowse.org",
                    path = "api/v1/Archives/StandardData", 
                    query = query)
}
```

I can simple query items using `queryAPI("json", "ACC")` but I'll get an error trying something like `queryAPI("json", c("ACC", "BRCA"))`. I'd love if the GET function would allow me to pass items like this and have another argument that asked for the separator to use when querying the API with multiple items (in this case, it'd be a comma).

In this case, it's easy to just do something like:
```r
queryAPI <- function(format, cohort) {
    if (!is.null(cohort))
        cohort <- paste(cohort, collapse = ",")

    query <- list(format = format, cohort = cohort)
    response <- GET("http://firebrowse.org",
                    path = "api/v1/Archives/StandardData", 
                    query = query)
}
```

However, my real function has 12 query attributes, not 1 like I show here. To simply modify the GET to have a `"collapse" = ","` instead of adding lots of lines of code would be great! Something like:
```r
queryAPI <- function(format, cohort) {
    query <- list(format = format, cohort = cohort)
    response <- GET("http://firebrowse.org",
                    path = "api/v1/Archives/StandardData", 
                    query = query,
                    collapse = ",")
}
```

And then I'd be able to simply do `queryAPI("json", c("ACC", "BRCA"))`.

**Comment by lawmauwa** [comment]
nuno-agostinho, I am running into the same issue, trying to make a post api with multiple attributes that need to be separated by comma. Trying to create the query list by using paste and collapse = ",", but httr keeps translating it to "%2C", which the server keeps rejecting the whole url string.

**Comment by nuno-agostinho** [comment]
@lawmauwa As you said, httr replaces commas by `%2C`. I hadn't noticed it because the API I'm using supports encoded characters. Could you show the code you're using for POST?

**Comment by jennybc** [comment]
Since this also seems to relate to encoding a query string, might be good to link this to #335.

**Comment by lawmauwa** [comment]
@nuno-agostinho This is the Trello API that I am trying to use. I have a card (card_id) that I am trying to add two members onto it. The API specification is that "idMembers" must be a list object separated by comma:

`
card_api_address <- paste0("https://api.trello.com/1/cards/", card_id)
r <- POST(card_api_address, query=list(idMembers=URLdecode("55a6608e1dd9ee02ace29c3e,530c9b880252aeef7efe6cec"), key=application_key, token=application_token))
`

This is what the url httr constructs:
`
"https://api.trello.com/1/cards/570e60c377dda1ca6107f41e?idMembers=55a6608e1dd9ee02ace29c3e%2C530c9b880252aeef7efe6cec&key=1f41e060e555d562ecec612774c40a29&token=5ed59b82474999b1f4d4cd4971f5f8e851b745c9f85f5d7234d76c6dd4b2003e"
`

But when I use parse_url(r$url), the query shows that it does indeed has a comma:
`
$scheme
[1] "https"

$hostname
[1] "api.trello.com"

$port
NULL

$path
[1] "1/cards/570e60c377dda1ca6107f41e"

$query
$query$idMembers
[1] "55a6608e1dd9ee02ace29c3e,530c9b880252aeef7efe6cec"
`

**Comment by hadley** [comment]
I don't see any evidence that the current behaviour is incorrect.  This returns the same as the request in the browser:

```R
content(GET("http://firebrowse.org",
  path = "api/v1/Metadata/Cohorts", 
  query = list(format = "json", cohort = "ACC,BRCA")
))
```

I don't think it would be any simpler for httr to do this as opposed to you simply using `paste()` yourself.

@lawmauwa I think you are confused about the value of the url and its representation.
