### ISSUE TITLE
Calling content() after httr::GET() returning read_csv() error

### ISSUE THREAD

**Issue by tomschenkjr** [hadley/httr#329]
Seem to have some issues with httr 1.1.0 and the use of `GET()` and `content()` in conjunction with each other.

For instance, running
```r
response <- httr::GET("https://soda.demo.socrata.com/resource/4334-bgaj.json")
content(response)
```

will return:
```r
Error: `col_names` must be TRUE, FALSE or a character vector
```

The traceback shows:
> 8 stop("`col_names` must be TRUE, FALSE or a character vector", 
    call. = FALSE) 
> 7 col_spec_standardise(data, skip = skip, comment = comment, n_max = n_max, 
    col_names = col_names, col_types = col_types, tokenizer = tokenizer, 
    locale = locale) 
> 6 read_delimited(file, tokenizer, col_names = col_names, col_types = col_types, 
    locale = locale, skip = skip, comment = comment, n_max = n_max, 
    progress = progress) 
> 5 readr::read_csv(x, readr::locale(encoding = encoding), ...) 
> 4 parser(content, type = type, encoding = encoding, ...) 
> 3 parse_auto(raw, type, encoding, ...) 
> 2 content(response) 

To get around this, one option for users is to use `content(response, as = "text")` and parse the text on your own. Just getting started on this, but unclear why `read_csv()` is rendering this error. The user cannot set options on `col_names` to precipitate or override the error, so reliant on `read_csv` `guess_header()` function.

// Issue was found during testing using `httr` in the most recent tests of `RSocrata`. See Chicago/RSocrata#75

**Comment by jennybc** [comment]
I think this would be fixed by https://github.com/hadley/httr/pull/331, at least for csv and tsv. I'm a bit confused above -- is your content JSON or comma/tab delimited?

**Comment by tomschenkjr** [comment]
Thanks! I'll try to test your pull request to see if that fixes the issue.

The content is CSV. When inputting JSON, it'll run fine.
