### ISSUE TITLE
Error with content() for JSON response

### ISSUE THREAD

**Issue by loganlinn** [hadley/httr#330]
I am getting an error with latest httr version when calling `content` on a JSON response. Here's a small reproduction:

```R
> httr::content(
+   httr::GET("https://status.github.com/api/status.json", encoding="UTF-8"),
+   type = "application/json",
+   simplifyVector = TRUE
+ )
Error in simplify(obj, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame,  :
  unused argument (encoding = NULL)
```

The error will actually go away if I don't use `simplifyVector` argument. But I think the real issue is lies in this change: https://github.com/hadley/httr/commit/f0fc278b96e8814c3527bb7a6ada19522d297df0#diff-de09a71ef56d7758b0d08b98fe0520eaL68

The `encoding` argument was removed from function signature and now gets passed to `jsonlite::fromJSON`. If I put `encoding = NULL` back in that signature, ie removing it from `...`, I no longer get the error

**Comment by s-r-k** [comment]
I am still receiving this error. Actually I am using another package that internally uses httr. Any workarounds? When can the solution be expected?

**Comment by alexdeng** [comment]
+1. hitted the same issue.

**Comment by maju116** [comment]
+1

**Comment by MarcinKosinski** [comment]
+1

**Comment by jeroenooms** [comment]
This needs to be fixed, but generally it is safer to extract the text and pass it to the parser yourself:

```r
req <- httr::GET("https://status.github.com/api/status.json")
text <- httr::content(req, "text", encoding="UTF-8")
data <- jsonlite::fromJSON(text)
```

**Comment by potockan** [comment]
+1
