### ISSUE TITLE
Implement JWT / keycloak

### ISSUE THREAD

**Issue by jeroenooms** [hadley/httr#332]
Reminder for myself. With jsonlite and openssl in the stack now, supporting [JWT](https://jwt.io/) should be ~~easy~~ doable.

**Comment by hadley** [comment]
I'm working on httr for a bit if you're interested in implementing

**Comment by jeroenooms** [comment]
I started something here a bit ago, don't remember how far I got: https://github.com/jeroenooms/jose

**Comment by jeroenooms** [comment]
I'm going to do the full JOSE/JWT/JWK spec.

**Comment by hadley** [comment]
Do you think this needs to go in httr, or is it ok in a separate package?

**Comment by jeroenooms** [comment]
I think if we implement all the JOSE stuff it's big enough and  useful in a separate package.
