### ISSUE TITLE
What's the proper way to get scopes?

### ISSUE THREAD

**Issue by jennybc** [hadley/httr#334]
Is this the most proper way to get the scopes associated with a token?

```
foo$params$scope
#> "https://spreadsheets.google.com/feeds" "https://www.googleapis.com/auth/drive"
```

For that matter, how do you list the methods that exist for an R6 class? I want to do `methods(class = "Token2.0")` but that clearly does not work. I wanted to see if, e.g., `foo$scopes()` would work.

**Comment by hadley** [comment]
I don't think there is a "proper" way.  I think you can do `ls(envir = foo)` to get all methods/fields.
