### ISSUE TITLE
encoding/decoding '+' as space (rather than literal '+' sign)

### ISSUE THREAD

**Issue by mpettis** [hadley/httr#335]
Without fully understanding RFC 1808, I think that in the query section of the URI that the '+' should not be translated to '%2B', which is a literal '+' sign, but to '%20', which is a space character.  For instance, you can see this:

    > library(httr)
    > 
    > url <- "http://google.com?q=saint+paul+mn"
    > 
    > parse_url(url)
    $scheme
    [1] "http"

    $hostname
    [1] "google.com"

    $port
    NULL

    $path
    [1] ""

    $query
    $query$q
    [1] "saint+paul+mn"

    $params
    NULL

    $fragment
    NULL

    $username
    NULL

    $password
    NULL

    attr(,"class")
    [1] "url"
    > 
    > build_url(parse_url(url))
    [1] "http://google.com/?q=saint%2Bpaul%2Bmn"

If you compare the original `url` to the parsed/built url, they generate different queries.  In the first case, the '+' signs are interpreted as spaces, but after parse/build, a literal '+' sign is passed.  The current behavior breaks some use cases.

I do not know if this is actually in compliance with RFC 1808 and there needs to be some pre-processing that needs to happen to make this not break, or it is not in compliance due to the meaning of the '+' in the query portion of the URI.

Also, I'll reference this in terms of this discussion: http://stackoverflow.com/a/29948396/1022967

**Comment by jennybc** [comment]
I think this treatment of `+` inside `query` explains some of the struggle I am having with GitHub search via the API.

Goal: use the API to do this search:

<https://github.com/search?utf8=✓&q=type%3Aissue+author%3Ahadley+repo%3Arstudio%2Frstudioapi+state%3Aopen>

``` r
library(httr)

query_space <- "type:issue author:hadley repo:rstudio/rstudioapi state:open"
query_plus <- "type:issue+author:hadley+repo:rstudio/rstudioapi+state:open"
list_space <- list(q = query_space)
list_plus <- list(q = query_plus)

(url <-
  modify_url("https://api.github.com", path = "search/issues", query = list_space))
#> [1] "https://api.github.com/search/issues?q=type%3Aissue%20author%3Ahadley%20repo%3Arstudio%2Frstudioapi%20state%3Aopen"
status_code(x <- GET(url))
#> [1] 200

(url <-
  modify_url("https://api.github.com", path = "/search/issues", query = list_plus))
#> [1] "https://api.github.com//search/issues?q=type%3Aissue%2Bauthor%3Ahadley%2Brepo%3Arstudio%2Frstudioapi%2Bstate%3Aopen"
status_code(x <- GET(url))
#> [1] 404

(url <- paste0("https://api.github.com/search/issues?q=", query_space))
#> [1] "https://api.github.com/search/issues?q=type:issue author:hadley repo:rstudio/rstudioapi state:open"
status_code(x <- GET(url))
#> [1] 400

(url <- paste0("https://api.github.com/search/issues?q=", query_plus))
#> [1] "https://api.github.com/search/issues?q=type:issue+author:hadley+repo:rstudio/rstudioapi+state:open"
status_code(x <- GET(url))
#> [1] 200
```

**Comment by mpettis** [comment]
I don't know if this helps, but I also gauged this against the analagous Python library to see how it would parse, and it parsed as I expected (as in: it returned the same url as I input, with `+` handled correctly.  It may be useful for test comparisons of the library working correctly.  It also references RFC1808 as one of the RFC's referenced in how it works (bottom of the Python docs page referenced below).

    #!/usr/bin/env python

    # Referenced: https://docs.python.org/2/library/urlparse.html
    # Run under Python 2.7.10

    from urlparse import urlparse, urlunparse

    url = "http://google.com?q=saint+paul+mn"

    o = urlparse(url)

        # Just retrieving the URL
    print(o.geturl())
    # Returns: http://google.com?q=saint+paul+mn

        # unparsing the parsed url -- is idempotent in this case
    print(urlunparse(o))
    # Returns: http://google.com?q=saint+paul+mn

**Comment by jennybc** [comment]
Encoding the query via base `URLencode()` vs `curl::curl_espace()` seems to help (see the PR). C.f. this bit of the [SO discussion linked above](http://stackoverflow.com/a/29948396/1022967):

> This means that the "blue+light blue" string has to be encoded differently in the path and query parts: "http://example.com/blue+light%20blue?blue%2Blight+blue". From there you can deduce that encoding a fully constructed URL is impossible without a syntactical awareness of the URL structure.

**Comment by hadley** [comment]
That is not my understanding - `+` is mostly a historical artefact, and now we should favour the standard percent encoding.  You'll need to reference the appropriate RFC to persuade me - I don't think 1808 is relevant here.

**Comment by mpettis** [comment]
I agree that 1808 is obsolete in that you need not produce strings that conform to that, but both @jennybc and I seem to have encountered problems consuming URIs that do conform to that.  It is aggravating that it is still produced (for me, by a Fortune 500 company that should know better).  I guess the question is: should httr just adopt the newer standard, and fail on URIs conforming to the older standard, or be more liberal, and hence complicated, in what it takes in?

If httr doesn't support it in the end, I personally will likely make myself a small utility (in Python or Perl or something), that preprocesses a URI to what httr will process.  I'd assume that's what others would do if support for this older spec isn't approved.

**Comment by hadley** [comment]
As far as I can tell RFC 1808 says nothing about how query strings are constructed.

**Comment by jjchern** [comment]
Probably related.

The Census Bureau's Annual Survey of Manufactures API has this [example url](http://api.census.gov/data/timeseries/asm/industry/examples.html): 

```
http://api.census.gov/data/timeseries/asm/industry?get=EMP,NAICS_TTL,GEO_TTL&for=us:*&time=2013&NAICS=31-33&key=YOUR_KEY_GOES_HERE
```

It seems `httr::build_url()` were not able to return special characters like `,`, `:`, and `*`.

```R
url = "http://api.census.gov/data/timeseries/asm/industry?get=EMP,NAICS_TTL,GEO_TTL&for=us:*&time=2013&NAICS=31-33&key=YOUR_KEY_GOES_HERE"
build_url(parse_url(url))

[1] "http://api.census.gov/data/timeseries/asm/industry?get=EMP%2CNAICS_TTL%2CGEO_TTL&for=us%3A%2A&time=2013&NAICS=31-33&key=YOUR_KEY_GOES_HERE"
```

**Comment by hadley** [comment]
If you don't want curl to escape query params, you can simply surround them with `I()`. I think that should be adequate to work around any server weirdness.
