### ISSUE TITLE
Error in open.connection(con, "rb") : HTTP error 500.

### ISSUE THREAD

**Issue by maaraaj** [hadley/httr#338]
I get this error on running 
fromJSON(file)

Please suggest how to debug this

**Comment by jeroenooms** [comment]
This means your server is down, this isunrelated to R/httr.

**Comment by maaraaj** [comment]
Thanks !! 

```
for (i in 1:10) { 
        n <- i
        from_date <- as.character(format(Sys.Date()-n, format="%Y%m%d"))
        to_date <- as.character(format(Sys.Date()-n, format="%Y%m%d"))
        
        url <- "https://api.xxxxxx.com/api/events.json?id=xxxxxxxxxxx&p=xxxxxxxxx&batch_size=4800"
        f <- paste0("{event_name:'xxxxxx',from:",from_date,",to:",to_date,"}")
        
        r <- POST(url,body = f)
        
        resp_id <- unlist(content(r, "parsed", "application/json"))["CONTENT.req_id"]
        
        url_resp <- paste0(url, "&req_id=")
        
        file <- paste0(url_resp, resp_id)
        jsonData <- fromJSON(file)
        Sys.sleep(2) 
        my_data <- jsonData$CONTENT$data
        write.csv(my_data, paste0("data", i, ".csv")
}
```

This is the code I am running 
most of the times I am getting these 2 errors::
1. Error in open.connection(con, "rb") : HTTP error 500.
2. Code runs completely but the 11th line rest_id returns NULL because of which my_data is NULL too. 

My connectivity is good .. Is it because of the client servers. 

Also... I want to insert a line in the loop in the end that closes all the HTTP connections.. Please suggest me how can I do that .

**Comment by hadley** [comment]
@maaraaj this is not the best place for getting help on how to use httr correctly.
