### ISSUE TITLE
About reuse handle and cookies data to subsequent requests

### ISSUE THREAD

**Issue by smendozabarrera** [hadley/httr#339]
# About reuse handle and cookies data to subsequent requests<a id="orgheadline1"></a>

Hello, in my scenery I login in a subdomain like
<http://login.server.com> then I want to load data from another
subdomain <http://othersubdomain.server.com> using the same session,
credentials and cookies. Tried to "httr" package to reuse the handle,
initiale I believe the httr package could manage the session data
automatically, but I am missing something because the cookies
definition are changing after I use the GET function in the second
read.

I need to read tens of pages with the same session.

Any ideas?

    ######################################################################
    ## Toy example

    library(httr)
    library(XML)

    rm(list = ls())

    handle <- handle("http://login.server.com")

    ## fields found in the login form.
    login <- list(
            loginId = "login",
            password  = "password"
    )

    response <- POST(handle = handle, body = login)
    http_status(response)
    cookies(response)

    ## First cookie vector
    cookie <- c(
            `server_apache_id` = "201.157.1.119.1455657637885.419040.2",
            `JSESSIONID` = "8DFE006224C8B023CB63E714CE277A30",
            `server_apache_track` = "",
            `server_apache_tracktmp` = "",
            `xman_us_f` = "x_l=0",
            `xman_t` = "JgrlUGEhA+3CICavo46Qqi0nGnroh4Bw99SvBGV4SBlA4FYhha64TGh+HhLnGnPMPJzLZuxVoAmIULr5sQihpCNblZd305U0",
            `acs_usuc_t` = "acs_rt=69488b534e594ff5965b6ca352a2361e",
            `xman_f` = "1LULrhjS1LNwR+RYT1y7R9CblzrDY57Mij3RAd2ml8lra3qKxzcYIRgD+CmT3t6PwDS7AqAAyEU6lIgZrs7JndN13T9+AhSg45PahyjtewO7GM44+4Q1FA==")

    URL <- "http://othersubdomain.server.com/item/data.html"

    html2 <- GET(URL, set_cookies(.cookies = cookie), user_agent("Mozilla/5.0"))
    http_status(html2)
    cookies(html2)                     # Completely different cookie data

    content2 <- content(html2, as <- "text")
    parsedHtml <- htmlParse(content2, asText <- TRUE)

    t <- try(unlist(xpathSApply(parsedHtml,
                                "//span[@id='some-data']", xmlValue))[1])

    if(("try-error" %in% class(t)) || is.null(t)) {
            writeLines(paste("\n :: Program broken at : URL = ", URL, sep = ""))
            break
    }

    writeLines(paste("\n :: Data verification, data = ", t, sep = ""))

**Thank you!**

**Comment by hadley** [comment]
It would be easier to answer your question if you supplied a minimal reprex, but I think all you need to do is re-use the same handle for every request.
