### ISSUE TITLE
Getting "error in strsplit(x, "")[[1]] : subscript out of bounds" when doing OAuth1.0 with Goodreads.com

### ISSUE THREAD

**Issue by dmpe** [hadley/httr#341]
Hello, 

When trying to create a package by using <https://www.goodreads.com/api/index> service, I have to use OAuth1.0. My code I use for that is provided below.

```
myGoodReadsApp <- httr::oauth_app("MyRTestApi", key = "7CECRDW0HnGsKmAJ8sjQ", secret = "Z8Pk4MJ4WPX1BefN6exBjkhs9vd74UfTnxDqz7LfQ")

test_end<- httr::oauth_endpoint("request_token", "authorize", "access_token",
                                                               base_url = "https://www.goodreads.com/oauth")

goodReads_token <- httr::oauth1.0_token(test_end, myGoodReadsApp, 
                                      as_header = T, cache = T)
```
When executing the above code, I can successfully authenticate on the goodreads.com and see "Authentication complete. Please close this page and return to R." message. However, when going back to RStudio, the console immediate prints: 
```
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in strsplit(x, "")[[1]] : subscript out of bounds <----- THIS
```
With that, the whole authentication is uncessfull and the token is not stored in the R environment. 

I can reproduce this behaviour on both versions of httr (1.0 and 1.1) and with recent r-devel on windows.
EDIT: on linux with r-release it also shows the same error

Any hints on what is wrong, Hadley ?
Thanks.

**Comment by dmpe** [comment]
According to https://github.com/hadley/httr/search?utf8=%E2%9C%93&q=strsplit%28x%2C+%22%22%29[[1]], this seems to be somewhere here https://github.com/hadley/httr/blob/master/R/oauth-signature.r#L103

**Comment by hadley** [comment]
This code works fine for me:

```R
app <- oauth_app("goodrrrreads",
  "X2ERJnp5ZjuXbA98P5pBLQ",
  "PKgK74tadSfC5DtOnQSdsYK5TVgl34XAIBvDpeYnDg0"
)

endp <- oauth_endpoint(
  "http://www.goodreads.com/oauth/request_token",
  "http://www.goodreads.com/oauth/authorize",
  "http://www.goodreads.com/oauth/access_token"
)

token <- oauth1.0_token(endp, app)
me <- content(GET("https://www.goodreads.com/api/auth_user", token))
```

**Comment by mkearney** [comment]
@hadley's code only worked for me when I converted the endpoint schemes to "https" (like the code below). Before that I was getting `Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401).`

``` r
app <- oauth_app("goodrrrreads",
  "X2ERJnp5ZjuXbA98P5pBLQ",
  "PKgK74tadSfC5DtOnQSdsYK5TVgl34XAIBvDpeYnDg0"
)

endp <- oauth_endpoint(
  "https://www.goodreads.com/oauth/request_token",
  "https://www.goodreads.com/oauth/authorize",
  "https://www.goodreads.com/oauth/access_token"
)

token <- oauth1.0_token(endp, app)
me <- content(GET("https://www.goodreads.com/api/auth_user", token))
```
