### ISSUE TITLE
hidemyass proxy list no longer avail. 

### ISSUE THREAD

**Issue by sckott** [hadley/httr#343]
wrt the docs for `use_proxy`

http://proxylist.hidemyass.com/ doesn't list proxy urls anymore. 

<img width="1218" alt="screen shot 2016-02-24 at 12 05 32 pm" src="https://cloud.githubusercontent.com/assets/577668/13299188/ed78780c-daee-11e5-9524-67c4d7f416ad.png">

**Comment by hadley** [comment]
Looks fine to me? You just have to scroll down the page a bit

**Comment by sckott** [comment]
sorry bout that, not sure how I missed that, given that i'd used it before
