### ISSUE TITLE
progress doesn't always add a newline

### ISSUE THREAD

**Issue by jennybc** [hadley/httr#344]
When the file size is unknown, I think `httr::progress()` somehow never executes [this line](https://github.com/hadley/httr/blob/a68c86c8777b9ef9bf49b8fea7af356d44d92735/R/progress.R#L47) and this can mess with the next thing getting printed, like this table.

```
Downloading: 2.3 MB                gs_read_csv gs_read_listfeed gs_read_cellfeed
user.self        0.042            0.324            1.798
sys.self         0.003            0.027            0.078
elapsed          1.091            1.471            3.479
user.child       0.000            0.000            0.000
sys.child        0.000            0.000            0.000
```

**Comment by hadley** [comment]
I'd be happy to review a PR - I'm not very good at working through logic puzzles like this

**Comment by jennybc** [comment]
I really wanted to fix this but I can't even figure out how `progress_bar()/show_progress()` gets called. I admit defeat.

**Comment by jeroenooms** [comment]
It looks like the line with `if (now == total) cat("\n")` should be moved out of the `if (total == 0){}` block? Currently it can never be reached because if `total == 0` and `now == 0` then the function already returns a few lines earlier...

**Comment by jennybc** [comment]
When the file size is unknown, `total` is always `0` anyway. So you have to add the newline when the download is over. But how to tell?

**Comment by jeroenooms** [comment]
@jennybc maybe we shouldn't show a progress bar in the first place if the total size is unknown?

**Comment by jennybc** [comment]
But it is really reassuring to watch the numbers change as the download progresses. Even the insertion of final file size in a non interactive thing is good too. I just wish it didn't mess with the next thing printed.

**Comment by hadley** [comment]
The problem is that there is no function that is currently called when the transfer is complete. This needs to be added as an httr option, and then `progress()` would set `completefunction = function() cat("\n")`

**Comment by hadley** [comment]
I think this is too low priority that I'll ever implement, and you can easily work around yourself with `cat("\n")` (or I'd review a PR)
