### ISSUE TITLE
Error in reset_handle

### ISSUE THREAD

**Issue by asieira** [hadley/httr#346]
After performing a few requests, I confirmed that there were handles in the handle pool for my destination. However, trying to reset it generates an error:
```

> handle_find("https://<redacted>")
Host: https://<redacted>/ <0x11ad60120>
> handle_reset("https://<redacted>")
Erro: inherits(handle, "curl_handle") is not TRUE

Enter a frame number, or 0 to exit   

1: handle_reset("https://<redacted>")
2: stopifnot(inherits(handle, "curl_handle"))
```

This was observed with httr 1.1.0 and curl 0.9.6 on R 3.2.4 for Mac OS X.

**Comment by hadley** [comment]
`handle_reset("http://google.com")` works for me.
