### ISSUE TITLE
write_stream: terminate handler function

### ISSUE THREAD

**Issue by Bart6114** [hadley/httr#352]
According to the help page on `write_stream(f)`:

```
f: Callback function. It should have a single argument, a raw vector containing the bytes recieved from the server. This will usually be 16k or less. It should return the length of bytes processed - if this is less than the input length, the function will terminate.
```

However, I don't think it currently checks the returned length of bytes processed. For example the below code will process just fine.

```r
GET("https://jeroenooms.github.io/data/diamonds.json",
    write_stream(function(x) {
      print(length(x))
      return(NULL)  # or any value
    })
)
```

Ideally I would like some way to terminate the handler (not just when the stream ends).

**Comment by hadley** [comment]
@jeroenooms is this an rcurl problem? Or am I passing the function in the wrong way?

**Comment by hadley** [comment]
Oh just read the curl thread. I'll update the docs.
