### ISSUE TITLE
progress: Output to stderr - not stdout

### ISSUE THREAD

**Issue by HenrikBengtsson** [hadley/httr#359]
# Issue
Download progress such as:
```
Downloading: 1.2 kB
```
is outputted to standard output (stdout).  This means for instance that the progress is captured by report generators.  Outputting to standard error (stderr) avoids this.

# Troubleshooting
This is because [`cat()` and `utils::txtProgressBar()` are called with defaults](https://github.com/hadley/httr/blob/7261a525ede1beb9880d1ce2e2009d27c8e8bef7/R/progress.R#L46-L53
), which results in output to stdout.  Passing `file=stderr()` to these functions would probably be enough.

Related code issues: Issue #344

**Comment by hadley** [comment]
I made it an option - I couldn't change the default because it breaks the default progress behaviour (each update gets a new line when using stderr)

**Comment by HenrikBengtsson** [comment]
Thanks.

Could you clarify what you mean by "each update gets a new line when using stderr"?  Why would `stdout()` and `stderr()` differ in what (character sequence) is outputted (other than to where)?  You're not referring to behavior of `message()` here, which shouldn't be involved, correct?

**Comment by hadley** [comment]
Just try it out yourself - `stderr()` doesn't seem to respond to "\r" in the same way as `stdout()` (at least in RStudio)

**Comment by HenrikBengtsson** [comment]
I see.  It seems to come down to how RStudio handles `\r` (CR) in the two cases.  Here's what I found using RStudio 0.99.902 (on Windows):

```r
## Ask expected
> cat("abc\rABC\n", file=stdout())
ABC
> cat("abc\rABC\n", file=stderr())
ABC

## Different behavior between stdout and stderr
> cat("abc", file=stdout()); cat("\rABC\n", file=stdout())
ABC
> cat("abc", file=stderr()); cat("\rABC\n", file=stderr())
abcABC

## Also, it seems as '\r' is "forgotten" between cat() regardless of output
> cat("abc\r", file=stdout()); cat("ABC\n", file=stdout())
abcABC
> cat("abc\r", file=stderr()); cat("ABC\n", file=stderr())
abcABC
```

I've tried this on Windows (Rterm and Rgui) as well as Linux and I cannot reproduce this there.
