### ISSUE TITLE
`.httr-oauth` file should be created with perms `0600` by default

### ISSUE THREAD

**Issue by craigcitro** [hadley/httr#365]
Title says it all -- I can't see a reason that we shouldn't default to creating the file with restrictive permissions. I'm happy to send a PR if folks agree.

**Comment by hadley** [comment]
PR would be awesome :)

**Comment by jennybc** [comment]
Could this make it hard to read `.httr-oauth` in some Shiny situations?

**Comment by daattali** [comment]
I agree, I also think this is going to introduce bugs to shiny users.

For example, shiny apps on a shiny server by default run as the "shiny" user, who is normally not the owner of the file, so shiny apps will get permission denied issues.  Is this correct, or am I missing something?
