### ISSUE TITLE
localtime warnings when using httr::GET

### ISSUE THREAD

**Issue by mtreadwell** [hadley/httr#367]
It is likely that I am doing something wrong so I am reaching out here:

    install.packages('httr')
    
    Sys.setenv(tz = 'UTC')
    options(tz = 'UTC')
    
    httr::GET('http://google.com')
    
    Warning messages:
    1: In strptime(x, fmt, tz = "GMT") :
      unable to identify current timezone 'C':
    please set environment variable 'TZ'
    2: In strptime(x, fmt, tz = "GMT") : unknown timezone 'localtime'

I've tried following the instructions here but with no luck: http://www.r-bloggers.com/doing-away-with-%E2%80%9Cunknown-timezone%E2%80%9D-warnings/

Does anyone esle have this issue or am I missing something simple?

**Comment by hadley** [comment]
Works for me.

**Comment by mtreadwell** [comment]
As info this was a bug with R-3.2.2

https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16503
