### ISSUE TITLE
Error in token$sign : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by msjgriffiths** [hadley/httr#369]
This seems related to #208, but since it appears to be different I'm making a new issue. 

I installed the dev version from Github, and the issue still occurs. Note that I also experienced #324 as [my comment](https://github.com/hadley/httr/issues/324#issuecomment-220458961) outlines. I have used that monkey patch to approach this point.

I'm trying to work through the Facebook demo. One of the lines is the [GET request](https://github.com/hadley/httr/blob/master/demo/oauth2-facebook.r#L17). The problem is that I receive an error.

```r
# fb_app setup as in the demo: https://github.com/hadley/httr/blob/master/demo/oauth2-facebook.r#L10.
fb_token <- oauth2.0_token(oauth_endpoints("facebook"), fb_app, cache = F)
GET("https://graph.facebook.com/me", config(token = "fb_token"))
> Error in token$sign : $ operator is invalid for atomic vectors
```

The problem appears to be in the [`Token2.0` class](https://github.com/hadley/httr/blob/f2c3c4d48ee5f32a77449fff578ebf05f5dd89a2/R/oauth-token.r#L235). In brief, there's this line:

```r
Authorization = paste('Bearer', self$credentials$access_token))
```

Unfortunately, for me, while I have a successful access token the `fb_token$credentials`, it looks like this:

```
> fb_token$credentials
[1] "access_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&expires=5161857"
```

This is obviously not parsed out.

I can work around this issue by patching the `$credentials` value to have an `$access_token` value, i.e.

```r
parsed_creds <- httr::parse_url(paste0("http://localhost/?", fb_token$credentials))
fb_token$credentials <- parsed_creds$query

req <- GET("https://graph.facebook.com/me", config(token = fb_token), verbose())
```

This completes fine, and returns the expected results.

**Comment by hadley** [comment]
Can you please verify that you still get this error when using the `oauth2-faebook` demo?  It works fine for me.  (Also for future reference, please don't supply `sessionInfo()` unless asked)

**Comment by msjgriffiths** [comment]
I refreshed from GitHub and it works like a charm now. Thanks!
