### ISSUE TITLE
Authentication fails over shinyapps.io

### ISSUE THREAD

**Issue by debsush** [hadley/httr#370]
Hi,

I am new to this world so excuse my ignorance.

oauth2-google.r works fine locally.  Now I have a webapp over shinyapps.io called https://dmarket.shinyapps.io/Main.   If I try to use the same code behind the login button so that users to my webapp can login via google, the shinyapps server does not allow it. I raised this in shinyapps forum and got a response back that shinyapps does not allow opening of localhost port 1410 as the callback URI.  I do not understand teh technicalities but I would appreciate if you could give me some tips as to how can I host a webapp over shinyapps and let my users login via googleauth

Reference: https://groups.google.com/forum/#!topic/shinyapps-users/THbYd_Z24Fg

Regards,
SD

**Comment by hadley** [comment]
I don't know if anyone knows how to do this currently.

**Comment by debsush** [comment]
I may have jumped the gun or may have posed the wrong question here, so apologies and let me try and explain the situation again.
If I want the users of my webapp to share the content of my webapp into their facebook timeline or login using their google credentials, how can I make it happen using shinyapp.  I have seen other java based websites enable users to share the content/link to their facebook timeline.  Do they create a separate token everytime a user tries to share the content or do they save the same token and using the same token, users can post the content to their individual facebook profile timelines?

I am new to this world so my questions may sound naive.

Regards
SD

**Comment by hadley** [comment]
I understand your problem - as far as I know, there is no current solution.

**Comment by debsush** [comment]
Does that mean if I host my own shinyserver or on AWS instead of in shinyapps.io, the feature will work?

**Comment by jennybc** [comment]
Take a look at [`googleAuthR`](https://github.com/MarkEdmondson1234/googleAuthR). It still uses `httr`, but targets Google auth specifically and works in Shiny apps. It definitely lets user log in with their own credentials. There's a demo app [here](https://mark.shinyapps.io/searchConsoleRDemo/). Click on the "Authenticate to get started here". *Hmm .... auth appears to work but I then I get "Disconnected from the server" almost immediately ... not sure what's up with that @MarkEdmondson1234.*

**Comment by MarkEdmondson1234** [comment]
Thanks @jennybc , I think that app in particular will fail if you have no Search Console websites verified, I'll publish a more generic example thats in the newest version.  

@debsush raised this as an issue earlier here too: https://github.com/MarkEdmondson1234/googleAuthR/issues/34 which I think can be solved via Google project settings: OAuth2 for websites can use web URLs (80 or 443) so if the normal URL is used for the redirect back you don't need to specify a port number as you do for localhost apps.

**Comment by MarkEdmondson1234** [comment]
@jennybc @debsush I've added a better example working on shinyapps.io https://mark.shinyapps.io/googleAuthRexample/
