### ISSUE TITLE
 oauth2.0_token error  with facebook API?

### ISSUE THREAD

**Issue by kasper2619** [hadley/httr#374]
I have a collection of facebook functions that relies on the httr package.

The usual procedure is that one has to set oauth app specs and facebook endpoints. Until recently this worked like a charm but now when I try to get the token by the oauth2.0_token function I get the error:

> Waiting for authentication in browser... Press Esc/Ctrl + C to abort Authentication complete. Fejl i init_oauth2.0(self$endpoint, self$app, scope = self$params$scope, : Bad Request (HTTP 400).

You see my code below:

```
facebook_app <- oauth_app("facebook", key = "XXXX", secret = "YYYY")
  # end point
  facebook_ep <- oauth_endpoint(
    authorize = "https://www.facebook.com/dialog/oauth",
    access = "https://graph.facebook.com/oauth/access_token")
  # token from endpoint and oauth
  fb.token <- oauth2.0_token(facebook_ep, facebook_app)
```

I have been to various posts and forums but I have not had luck in finding a solution yet. Also I tried from my work network and my home network with three different pc'es (2 times Ubuntu OS + 1 Windows OS)

It worked a month ago or so...

**Comment by kasper2619** [comment]
Solved by setting:

`Sys.setenv("HTTR_SERVER_PORT" = "1410/")`

**Comment by tokumotion** [comment]
Got the same problem with this code:

`oauth_callback()

oauth_endpoints("facebook")

app <- oauth_app('facebook', "XXXX", 
                 "XXXX")
Sys.setenv("HTTR_SERVER_PORT" = "1410/")
fb_token <- oauth2.0_token(oauth_endpoints("facebook"), app,
                           scope = c("ads_management", 'read_insights'),
                           type  = "application/x-www-form-urlencoded", 
                           cache = FALSE)
save(fb_token, file = "~/Documents/fb_token")`

The message I receive is:

`Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in init_oauth2.0(self$endpoint, self$app, scope = self$params$scope,  : 
  Bad Request (HTTP 400). Failed to get an access token.`

**Comment by peeyooshc** [comment]
I'm having the same issue but using a mac osx, with httr 1.2.1 and authenticating with Chrome. Works fine with the example but not with my app - any advice other than shifting to a PC?

**Comment by tokumotion** [comment]
with new version of `httr` there is no need for this line of code:

`Sys.setenv("HTTR_SERVER_PORT" = "1410/")`
