### ISSUE TITLE
How to create an interactive environment within shinyapp

### ISSUE THREAD

**Issue by debsush** [hadley/httr#377]
Hi,

I am using the below query in sever.R and it works fine when run locally.  Howvere, when the app is deployed over shinyapps.io, I get the following error

Error:  Requires an interactive environment 

Code:

updateStatus <- function(text, token, link=NULL) {
  ## text prepocessing
  text <- enc2utf8(text)
  text <- gsub(" ", "+",text)
  
  ## query including text
  query <- paste('https://graph.facebook.com/me/feed?message=', text, sep="")
  ## adding URL
  if (!is.null(link)){
    query <- paste(query, "&link=", link, sep="")
  }
  ## making query
  if (class(token)[1]=="config"){
    url.data <- POST(query, config=token)
  }
  if (class(token)[1]=="Token2.0"){
    url.data <- POST(query, config(token=token))
  }  
  if (class(token)[1]=="character"){
    url <- paste0(query, "&access_token=", token)
    url.data <- POST(url)
  }
  if (class(token)[1]!="character" & class(token)[1]!="config" & class(token)[1]!="Token2.0") {
    stop("Error in access token. See help for details.")
  }
  ## output
  if (url.data$status_code==200){
    id <- fromJSON(rawToChar(url.data$content))$id
    if (is.null(id)){
      message("Failed update. OAuth token does not have permission to update status. ",
              "See ?fbOAuth for more details.")
    }
    message("Success! Link to status update: ", paste("http://www.facebook.com/", id, sep=""))
  }
  if (url.data$status_code==400){
    error <- fromJSON(rawToChar(url.data$content))$error$code
    message <- fromJSON(rawToChar(url.data$content))$error$message
    if (error==2500){
      message("Failed update. OAuth token does not have permission to update status. ",
              "See ?fbOAuth for more details.")
    }
    if (error!=2500){
      message("Failed update.", message)
    }
  }
}

observeEvent(input$FBButton,{
        Sys.setenv("HTTR_SERVER_PORT" = "1410/")
        updateStatus(paste("Analysis by using www.abc.com",sep=""), 
                     token=oauth2.0_token(oauth_endpoints('facebook'), 
                                          oauth_app('facebook', '1574265286199514', '8a99934b97206ad64c533bcbb6766f04'),
                                          scope = 'ads_management',
                                          type  = 'application/x-www-form-urlencoded', 
                                          cache = FALSE)$credentials$access_token, 
                     link = "www.rstudio.com")
})

**Comment by hadley** [comment]
It's not currently easy - you'll need to check in your `.httr-oauth`.
