### ISSUE TITLE
Better API client testing

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/httr#408]
## Motivation

One way to test API clients without performing thousands of requests all the time, is to record the requests and responses and then replay them while testing. There are tools for this in other languages as well. I wrote a very simple tool for R and `httr`: https://github.com/gaborcsardi/httrmock

Unfortunately, without modifications in `httr` itself, `httrmock` is hacky and fragile, it relies on tracing `httr` functions. With some minimal support from `httr` we could make it much better, and CRAN-grade proper.

## The callback option

The idea is that `httr` would get a callback option, and if this is turned on, then the callback function can determine whether to perform the actual HTTP requests. 

The callback function would be called (if installed) both at the beginning of `request_perform` and at the end, and `httr` would pass both the HTTP `request` and the `response` to the callback. `httrmock and possibly other packages can then implement API client testing, and HTTP request recording and replaying easily. 

Sg like this would go to the beginning of `request_perform`:

```r
if (! is.null(httr_callback)) {
  cbres <- httr_callback(mode = "request", req)
  if (!is.null(cbres)) return(cbres)
}
```

The callback is called with the request, and if it returns non-`NULL`, then we terminate early, without actually performing the request. This is *replay* mode, and the callback must return a proper response in this case.

If the callback returns `NULL`, then the request is performed.

Sg like this would go to the end of `request_perform`:

```r
res <- response(...)  etc.
if (! is.null(httr_callback)) {
  callback(mode = "response", req, res)
}
res
```

This is to allow the *recording* of the request.

Please let me know if this is something you would consider adding to `httr` and then I can put together a simple PR. Thanks!

**Comment by gaborcsardi** [comment]
@sckott would such a callback enough for your packages?

**Comment by hadley** [comment]
I think that's ok. I'm planning for httr2 in the next six months so I'm ok if the PR is slightly hacky. We can think it through in more depth for the next version.

**Comment by gaborcsardi** [comment]
@hadley I submitted a PR: #409 

It is not hacky imo, wrt httr at least, it is simply a classic callback hook.

**Comment by sckott** [comment]
@gaborcsardi possibly, but I think I'm moving forward with `crul`/`webmockr`
