### ISSUE TITLE
OAuth - AuthCode with PKCE (without secret)

### ISSUE THREAD

**Issue by m-mohr** [hadley/httr#705]
We are using the OAuth 2.0 functionality. It seems that httr is only supporting the AuthCode flow without PKCE (i.e. you need to provide a client secret). Is there a way to use AuthCode (or Device Code) with PKCE and thus without a client secret? If not, are there any plans to implement this?

**Comment by jennybc** [comment]
I think you should look at httr2:

https://httr2.r-lib.org
