### ISSUE TITLE
Error in credentials$access_token :    $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by kennethzfeng** [hadley/httr#96]
Hi,

I got the $ operator is invalid error while trying out the oauth2-facebook.r demo.  It looks like the credentials field of the OAuth2.0Token class is not a list but a character vector of misparsed encoded url parameters.

I am using the master branch version of httr (e9940ede4176a62f1117771f59e11c7bc58974a6)

Here is my version of the Facebook OAuth2 demo:

```
kFacebookAppID <- "******************************"
kFacebookAppSecret <- "**************************"

app <- oauth_app("facebook", key=kFacebookAppID, secret=kFacebookAppSecret)
endpoint <- oauth_endpoints("facebook")
token = oauth2.0_token(endpoint=endpoint, app, 
                  type="application/x-www-form-urlencoded")
html <- GET("https://graph.facebook.com/me", config(token=token))
```

Here is the traceback:

```
> traceback()
6: paste("Bearer", credentials$access_token)
5: add_headers(Authorization = paste("Bearer", credentials$access_token))
4: token$sign(method, url)
3: sign(config$token, method, url, config)
2: make_request("get", hu$handle, hu$url, config)
1: GET("https://graph.facebook.com/me", config(token = token))
```

It looks likes the init_oauth2.0 call doesn't return the parsed version of the url as a list.

I was able to work around the issue with the following:

```
access_token <- token$credentials[1]
parts <- unlist(strsplit(access_token, "&"))
credentials <- list()
credentials[["access_token"]] = strsplit(parts[[1]], "=")[[1]][2]
token$credentials <- credentials
```

Please excuse my poor R code quality as I just started programming in R.

Thanks,
Kenneth

**Comment by Timpop** [comment]
for me i did a work like urs but for GitHub

and my error show that:  token$sign : $ operator is invalid for atomic vectors 

and i just change relate code :

gtoken <- config(token = "your_token_c078863d08ff4007ae3dc24c")

to

gtoken <- config(token == "your_token_c078863d08ff4007ae3dc24c")

double ==

hop it would be helpful!!
